/**
 * Player-1 playability harness for SquidGame100 MineCraft (Stage 0).
 *
 * Drives the running Vite dev server (http://localhost:5173) with Playwright and
 * captures HARD NUMBERS across six axes:
 *   1. Frame pacing   — instrument REAL requestAnimationFrame over ~2s wall time
 *   2. Load/onboarding — navigation timing, FCP, long tasks, JS heap
 *   3. Input feel     — title-card dismiss on pointerdown + keydown (opacity -> 0)
 *   4. HUD legibility — computed contrast ratios vs WCAG AA 4.5:1
 *   5. Resilience     — viewport resize (desktop <-> mobile) + visibilitychange
 *   6. GPU/WebGL      — context, webgl2, renderer string, game-code console warns
 *
 * Uses the deterministic hooks documented in packages/client/AGENTS.md:
 *   window.render_game_to_text()  /  window.advanceTime(ms)
 *
 * Writes under .harness/qa/playability/:
 *   <run-id>.json        raw structured report
 *   <run-id>-*.png       screenshots (load, post-dismiss, mobile, post-resize)
 *   playability-report.md  human summary (generated by the report builder step)
 *
 * Does NOT touch game source. Mirrors the smoke harness idiom.
 *
 * NOTE: functions used inside page.evaluate() MUST be defined inside that
 * evaluate's function body — the browser context cannot see Node closures.
 */

import { chromium } from 'playwright';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const DIR = path.resolve(process.cwd(), '.harness/qa/playability');
const CLIENT_URL = process.env.WEB_GAME_CLIENT ?? 'http://localhost:5173/';
const RUN_ID =
  process.env.PLAYABILITY_RUN_ID ??
  `play-${new Date().toISOString().replace(/[:.]/g, '-')}`;

const DESKTOP = { width: 1920, height: 1080 };
const MOBILE = { width: 375, height: 812 };

const JANK_MS = 33; // frame interval threshold for "jank"
const SAMPLE_MS = 2000; // wall-time window for frame pacing

// ---- Node-side helpers (for post-processing collected numbers) ------------
function quantile(sortedArr, q) {
  if (!sortedArr.length) return null;
  const pos = (sortedArr.length - 1) * q;
  const base = Math.floor(pos);
  const rest = pos - base;
  const next = sortedArr[base + 1];
  return next !== undefined
    ? sortedArr[base] + rest * (next - sortedArr[base])
    : sortedArr[base];
}
function median(sortedArr) {
  return quantile(sortedArr, 0.5);
}
function round(n, d = 3) {
  const f = 10 ** d;
  return Math.round((n + Number.EPSILON) * f) / f;
}

async function main() {
  await mkdir(DIR, { recursive: true });

  const browser = await chromium.launch({ headless: true });
  const ctx = await browser.newContext({ viewport: DESKTOP });
  const page = await ctx.newPage();

  const consoleErrors = [];
  const consoleWarns = [];
  const pageErrors = [];
  const requestFailures = [];

  page.on('console', (msg) => {
    const t = msg.type();
    if (t === 'error') consoleErrors.push({ text: msg.text(), location: msg.location() });
    else if (t === 'warning') consoleWarns.push({ text: msg.text(), location: msg.location() });
  });
  page.on('pageerror', (err) => {
    pageErrors.push({ name: err.name, message: err.message, stack: err.stack });
  });
  page.on('requestfailed', (req) => {
    requestFailures.push({ url: req.url(), failure: req.failure()?.errorText });
  });

  // Init script: (a) patch WebSocket like the smoke harness, (b) instrument REAL
  // requestAnimationFrame to record frame intervals, (c) set up a longtask
  // observer. All installed BEFORE navigation so we capture the real RAF loop
  // the scene boots.
  await page.addInitScript(() => {
    const w = window;
    const r3 = (n) => Math.round((n + Number.EPSILON) * 1000) / 1000;

    // --- WS patch (mirrors smoke harness) ---
    w.__wsFrames = [];
    w.__wsState = { opened: 0, closed: 0, errored: 0, lastUrl: null };
    const Orig = w.WebSocket;
    function Patched(url, protocols) {
      const sock = new Orig(url, protocols);
      w.__wsState.lastUrl = url;
      const record = (dir, payload) => {
        try {
          w.__wsFrames.push({
            dir,
            t: Date.now(),
            payload: typeof payload === 'string' ? payload.slice(0, 4096) : '<binary>',
          });
          if (w.__wsFrames.length > 200) w.__wsFrames.shift();
        } catch {}
      };
      sock.addEventListener('open', () => {
        w.__wsState.opened += 1;
        record('state', JSON.stringify({ event: 'open', url }));
      });
      const origSend = sock.send.bind(sock);
      sock.send = function (data) {
        record('out', typeof data === 'string' ? data : '<binary>');
        return origSend(data);
      };
      sock.addEventListener('message', (ev) => {
        record('in', typeof ev.data === 'string' ? ev.data : '<binary>');
      });
      sock.addEventListener('close', (ev) => {
        w.__wsState.closed += 1;
        record('state', JSON.stringify({ event: 'close', code: ev.code }));
      });
      sock.addEventListener('error', () => {
        w.__wsState.errored += 1;
        record('state', JSON.stringify({ event: 'error' }));
      });
      return sock;
    }
    Patched.prototype = Orig.prototype;
    Object.defineProperty(Patched, 'CONNECTING', { value: Orig.CONNECTING });
    Object.defineProperty(Patched, 'OPEN', { value: Orig.OPEN });
    Object.defineProperty(Patched, 'CLOSING', { value: Orig.CLOSING });
    Object.defineProperty(Patched, 'CLOSED', { value: Orig.CLOSED });
    w.WebSocket = Patched;

    // --- RAF instrumentation (the dev server's REAL RAF) ---
    w.__raf = { intervals: [], active: true, lastCbTs: null, lastTs: null };
    const origRAF = w.requestAnimationFrame.bind(w);
    w.requestAnimationFrame = function (cb) {
      return origRAF((ts) => {
        if (w.__raf.active) {
          if (w.__raf.lastCbTs !== null) {
            w.__raf.intervals.push(r3(ts - w.__raf.lastCbTs));
          }
          w.__raf.lastCbTs = ts;
          w.__raf.lastTs = ts;
        }
        cb(ts);
      });
    };

    // --- Longtask observer ---
    w.__longTasks = [];
    try {
      const obs = new PerformanceObserver((list) => {
        for (const e of list.getEntries()) {
          w.__longTasks.push({ duration: Math.round((e.duration + Number.EPSILON) * 100) / 100, startTime: Math.round((e.startTime + Number.EPSILON) * 100) / 100 });
        }
      });
      obs.observe({ entryTypes: ['longtask'] });
      w.__longtaskObserver = obs;
    } catch {}
  });

  // ===================== AXIS 2: LOAD / ONBOARDING ========================
  const navResp = await page.goto(CLIENT_URL, { waitUntil: 'networkidle', timeout: 15000 });
  const navStatus = navResp ? navResp.status() : null;

  // Wait for the deterministic test hooks to be installed by the scene module.
  await page.waitForFunction(
    () => typeof window.render_game_to_text === 'function' && typeof window.advanceTime === 'function',
    null,
    { timeout: 5000 },
  );

  const loadMetrics = await page.evaluate(() => {
    const r3 = (n) => Math.round((n + Number.EPSILON) * 1000) / 1000;
    const nav = performance.getEntriesByType('navigation')[0] || null;
    const paintEntries = performance.getEntriesByType('paint');
    const fcp = paintEntries.find((p) => p.name === 'first-contentful-paint');
    const mem = performance.memory
      ? {
          usedJSHeapSize: performance.memory.usedJSHeapSize,
          totalJSHeapSize: performance.memory.totalJSHeapSize,
          jsHeapSizeLimit: performance.memory.jsHeapSizeLimit,
        }
      : null;
    return {
      navigation: nav
        ? {
            name: nav.name,
            ttfb: r3(nav.responseStart - nav.requestStart),
            domContentLoaded: r3(nav.domContentLoadedEventEnd - nav.startTime),
            domComplete: r3(nav.domComplete - nav.startTime),
            loadEventEnd: r3(nav.loadEventEnd - nav.startTime),
            transferSize: nav.transferSize,
            encodedBodySize: nav.encodedBodySize,
          }
        : null,
      firstContentfulPaint: fcp ? r3(fcp.startTime) : null,
      memory: mem,
    };
  });

  await page.screenshot({ path: path.join(DIR, `${RUN_ID}-01-load.png`) });

  // ===================== AXIS 1: FRAME PACING =============================
  // Reset and collect REAL RAF intervals over SAMPLE_MS wall time.
  await page.evaluate(() => {
    window.__raf.intervals = [];
    window.__raf.lastCbTs = null;
    window.__raf.active = true;
  });
  const rafStart = Date.now();
  await page.waitForTimeout(SAMPLE_MS + 300);
  const rafRaw = await page.evaluate(() => window.__raf.intervals.slice());
  const rafDur = Date.now() - rafStart;
  const rafSorted = [...rafRaw].sort((a, b) => a - b);
  const framePacing = {
    sampleWallMs: rafDur,
    frameCount: rafRaw.length,
    estimatedFps: rafRaw.length ? round(rafRaw.length / (rafDur / 1000), 2) : null,
    medianIntervalMs: rafRaw.length ? round(median(rafSorted), 3) : null,
    p95IntervalMs: rafRaw.length ? round(quantile(rafSorted, 0.95), 3) : null,
    maxGapMs: rafRaw.length ? round(rafSorted[rafSorted.length - 1], 3) : null,
    jankFramesGt33ms: rafRaw.filter((x) => x > JANK_MS).length,
    intervals: rafRaw,
  };

  // ===================== AXIS 3: INPUT FEEL ===============================
  // (a) pointerdown dismiss
  const inputPointer = await page.evaluate(() => {
    const el = document.getElementById('title-card');
    const before = el ? getComputedStyle(el).opacity : null;
    window.dispatchEvent(new PointerEvent('pointerdown', { bubbles: true }));
    return { opacityBefore: before };
  });
  // wait for the 0.6s transition
  await page.waitForTimeout(850);
  const pointerAfter = await page.evaluate(() => {
    const el = document.getElementById('title-card');
    return el ? { opacity: getComputedStyle(el).opacity, display: getComputedStyle(el).display } : null;
  });
  await page.screenshot({ path: path.join(DIR, `${RUN_ID}-02-post-dismiss.png`) });

  // (b) keydown dismiss on a fresh page (the { once: true } listener was already
  // consumed by pointerdown above), so reload to test keydown path in isolation.
  const ctx2 = await browser.newContext({ viewport: DESKTOP });
  const page2 = await ctx2.newPage();
  page2.on('console', () => {});
  await page2.goto(CLIENT_URL, { waitUntil: 'networkidle', timeout: 15000 });
  await page2.waitForFunction(
    () => typeof window.render_game_to_text === 'function',
    null,
    { timeout: 5000 },
  );
  const keydownBefore = await page2.evaluate(() => {
    const el = document.getElementById('title-card');
    return el ? getComputedStyle(el).opacity : null;
  });
  await page2.keyboard.down('Space');
  await page2.waitForTimeout(850);
  const keydownAfter = await page2.evaluate(() => {
    const el = document.getElementById('title-card');
    return el ? { opacity: getComputedStyle(el).opacity } : null;
  });
  await ctx2.close();

  const inputFeel = {
    pointerdown: {
      opacityBefore: inputPointer.opacityBefore,
      opacityAfter: pointerAfter?.opacity ?? null,
      displayAfter: pointerAfter?.display ?? null,
      fadedToZero: pointerAfter?.opacity === '0',
    },
    keydown: {
      opacityBefore: keydownBefore,
      opacityAfter: keydownAfter?.opacity ?? null,
      fadedToZero: keydownAfter?.opacity === '0',
    },
  };

  // ===================== AXIS 4: HUD LEGIBILITY ===========================
  const hudLegibility = await page.evaluate(() => {
    const r3 = (n) => Math.round((n + Number.EPSILON) * 1000) / 1000;
    function parseRgb(str) {
      if (!str) return null;
      const m = str.match(/rgba?\(([^)]+)\)/i);
      if (!m) return null;
      const p = m[1].split(',').map((s) => parseFloat(s.trim()));
      return p.length >= 3 ? [p[0], p[1], p[2]] : null;
    }
    function relLuminance(rgb) {
      const ch = rgb.map((c) => {
        const s = c / 255;
        return s <= 0.03928 ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4;
      });
      return 0.2126 * ch[0] + 0.7152 * ch[1] + 0.0722 * ch[2];
    }
    function contrastRatio(a, b) {
      const l1 = relLuminance(a);
      const l2 = relLuminance(b);
      const [hi, lo] = l1 > l2 ? [l1, l2] : [l2, l1];
      return (hi + 0.05) / (lo + 0.05);
    }
    // Composite an rgba() background over a solid rgb backdrop (alpha blend).
    function compositeAlpha(rgbaStr, overRgb) {
      const m = rgbaStr && rgbaStr.match(/rgba?\(([^)]+)\)/i);
      if (!m) return overRgb;
      const parts = m[1].split(',').map((s) => parseFloat(s.trim()));
      const [r, g, b] = parts;
      const a = parts.length >= 4 ? parts[3] : 1;
      return [
        Math.round(r * a + overRgb[0] * (1 - a)),
        Math.round(g * a + overRgb[1] * (1 - a)),
        Math.round(b * a + overRgb[2] * (1 - a)),
      ];
    }

    function probe(elId) {
      const el = document.getElementById(elId);
      if (!el) return null;
      const cs = getComputedStyle(el);
      const rect = el.getBoundingClientRect();
      return {
        color: cs.color,
        backgroundColor: cs.backgroundColor,
        fontSize: cs.fontSize,
        text: (el.textContent || '').trim().slice(0, 120),
        visible: rect.width > 0 && rect.height > 0,
        rect: { x: r3(rect.x), y: r3(rect.y), w: r3(rect.width), h: r3(rect.height) },
      };
    }

    const INK = [0x0b, 0x1f, 0x3a]; // --sg-ink #0b1f3a

    const status = probe('status');
    const title = document.querySelector('#title-card h1');
    const titleProbe = title
      ? (() => {
          const cs = getComputedStyle(title);
          const r = title.getBoundingClientRect();
          return {
            color: cs.color,
            fontSize: cs.fontSize,
            text: (title.textContent || '').trim().slice(0, 120),
            visible: r.width > 0 && r.height > 0,
          };
        })()
      : null;
    const cross = document.querySelector('.crosshair');
    const crossProbe = cross
      ? (() => {
          const cs = getComputedStyle(cross);
          const r = cross.getBoundingClientRect();
          return { width: cs.width, height: cs.height, opacity: cs.opacity, visible: r.width > 0 && r.height > 0 };
        })()
      : null;

    // status: text color vs composited background (status bg is rgba(ink,0.6) over scene)
    const statusTextRgb = parseRgb(status?.color);
    const statusBgRgb = compositeAlpha(status?.backgroundColor, INK);
    const statusContrast =
      statusTextRgb && statusBgRgb ? r3(contrastRatio(statusTextRgb, statusBgRgb)) : null;

    // title: text color vs scene background (ink)
    const titleTextRgb = parseRgb(titleProbe?.color);
    const titleContrast = titleTextRgb ? r3(contrastRatio(titleTextRgb, INK)) : null;

    return {
      status,
      title: titleProbe,
      crosshair: crossProbe,
      sceneBackgroundHex: '#0b1f3a',
      contrast: {
        statusTextVsBg: statusContrast,
        titleTextVsScene: titleContrast,
        wcagAATarget: 4.5,
      },
    };
  });

  // ===================== AXIS 5: RESILIENCE ===============================
  // (a) resize desktop -> mobile -> desktop, confirm canvas + camera recover.
  const resizeSeq = [];
  resizeSeq.push({
    label: 'desktop-1920x1080',
    canvas: await page.evaluate(() => {
      const c = document.getElementById('scene');
      return { clientW: c?.clientWidth ?? null, clientH: c?.clientHeight ?? null, w: c?.width ?? null, h: c?.height ?? null };
    }),
  });

  await page.setViewportSize(MOBILE);
  await page.waitForTimeout(400);
  resizeSeq.push({
    label: 'mobile-375x812',
    canvas: await page.evaluate(() => {
      const c = document.getElementById('scene');
      return { clientW: c?.clientWidth ?? null, clientH: c?.clientHeight ?? null, w: c?.width ?? null, h: c?.height ?? null };
    }),
  });
  await page.screenshot({ path: path.join(DIR, `${RUN_ID}-03-mobile.png`) });

  await page.setViewportSize(DESKTOP);
  await page.waitForTimeout(400);
  resizeSeq.push({
    label: 'desktop-restored',
    canvas: await page.evaluate(() => {
      const c = document.getElementById('scene');
      return { clientW: c?.clientWidth ?? null, clientH: c?.clientHeight ?? null, w: c?.width ?? null, h: c?.height ?? null };
    }),
    // verify camera aspect updated by reading render_game_to_text + a known hook
    hooksStillWork: await page.evaluate(() => {
      try {
        const t = window.render_game_to_text();
        window.advanceTime(16);
        return { renderOk: typeof t === 'string', advanceOk: true, sample: t.slice(0, 80) };
      } catch (e) {
        return { renderOk: false, error: String(e) };
      }
    }),
  });
  await page.screenshot({ path: path.join(DIR, `${RUN_ID}-04-post-resize.png`) });

  const hasZeroDim = resizeSeq.some((s) => s.canvas && (s.canvas.clientW === 0 || s.canvas.clientH === 0));

  // (b) visibilitychange hidden -> visible, confirm RAF resumes + hooks work.
  const visibilityTest = await page.evaluate(async () => {
    const beforeCount = window.__raf.intervals.length;
    window.__raf.active = true;
    const stateChanges = [];
    const visPoll = { hidden: false };
    try {
      Object.defineProperty(document, 'hidden', { configurable: true, get: () => visPoll.hidden });
      visPoll.hidden = true;
      document.dispatchEvent(new Event('visibilitychange'));
      stateChanges.push('hidden');
      await new Promise((r) => setTimeout(r, 250));
      visPoll.hidden = false;
      document.dispatchEvent(new Event('visibilitychange'));
      stateChanges.push('visible');
      await new Promise((r) => setTimeout(r, 600));
    } catch (e) {
      stateChanges.push('error:' + String(e));
    }
    const afterCount = window.__raf.intervals.length;
    let hooksOk = false;
    try {
      const t = window.render_game_to_text();
      window.advanceTime(16);
      hooksOk = typeof t === 'string';
    } catch (e) {
      hooksOk = 'error:' + String(e);
    }
    return {
      stateChanges,
      rafIntervalsBefore: beforeCount,
      rafIntervalsAfter: afterCount,
      rafAdvancedAfterVisible: afterCount > beforeCount,
      hooksOk,
    };
  });

  const resilience = {
    resize: { sequence: resizeSeq, anyZeroDimension: hasZeroDim },
    visibility: visibilityTest,
  };

  // ===================== AXIS 6: GPU / WEBGL ==============================
  const gpu = await page.evaluate(() => {
    const c = document.getElementById('scene');
    if (!c) return { hasCanvas: false };
    const gl = c.getContext('webgl2') || c.getContext('webgl');
    let vendor = null;
    let renderer = null;
    let webglVersion = null;
    let unmaskedVendor = null;
    let unmaskedRenderer = null;
    if (gl) {
      webglVersion = gl.getParameter(gl.VERSION);
      const dbg = gl.getExtension('WEBGL_debug_renderer_info');
      if (dbg) {
        unmaskedVendor = gl.getParameter(dbg.UNMASKED_VENDOR_WEBGL);
        unmaskedRenderer = gl.getParameter(dbg.UNMASKED_RENDERER_WEBGL);
      }
      vendor = gl.getParameter(gl.VENDOR);
      renderer = gl.getParameter(gl.RENDERER);
    }
    return {
      hasCanvas: true,
      hasWebGL2: !!c.getContext('webgl2'),
      webglVersion,
      vendor,
      renderer,
      unmaskedVendor,
      unmaskedRenderer,
    };
  });

  // ===================== FINAL STATE =======================================
  const finalText = await page.evaluate(() => window.render_game_to_text());
  const finalWs = await page.evaluate(() => ({ ...window.__wsState, frames: window.__wsFrames.slice() }));
  const longTasks = await page.evaluate(() => window.__longTasks.slice());
  const canvasInfo = await page.evaluate(() => {
    const c = document.getElementById('scene');
    if (!c) return null;
    return { width: c.width, height: c.height, clientW: c.clientWidth, clientH: c.clientHeight };
  });

  await browser.close();

  // ===================== REPORT ============================================
  // Filter out Playwright screenshot readback noise (ReadPixels GPU stall)
  // from the "game code" warning bucket.
  const GPU_NOISE = /ReadPixels|GPU stall/i;
  const gameWarns = consoleWarns.filter((w) => !GPU_NOISE.test(w.text));
  const noiseWarns = consoleWarns.filter((w) => GPU_NOISE.test(w.text));

  const report = {
    runId: RUN_ID,
    clientUrl: CLIENT_URL,
    generatedAt: new Date().toISOString(),
    viewportDesktop: DESKTOP,
    viewportMobile: MOBILE,
    navStatus,
    canvas: canvasInfo,
    axis1_framePacing: framePacing,
    axis2_load: { ...loadMetrics, longTasksCount: longTasks.length, longTasks: longTasks.slice(0, 20) },
    axis3_inputFeel: inputFeel,
    axis4_hudLegibility: hudLegibility,
    axis5_resilience: resilience,
    axis6_gpu: gpu,
    console: {
      gameWarnings: gameWarns,
      screenshotReadbackNoiseWarnings: noiseWarns.length,
      errors: consoleErrors,
      pageErrors,
      requestFailures,
    },
    network: { wsState: finalWs, finalTextSample: finalText?.slice(0, 200) ?? null },
  };

  const reportPath = path.join(DIR, `${RUN_ID}.json`);
  await writeFile(reportPath, JSON.stringify(report, null, 2), 'utf8');

  // Console summary line.
  console.log(`PLAYABILITY RUN ${RUN_ID}`);
  console.log(`  navStatus=${navStatus}`);
  console.log(`  framePacing: fps=${framePacing.estimatedFps} median=${framePacing.medianIntervalMs}ms p95=${framePacing.p95IntervalMs}ms max=${framePacing.maxGapMs}ms jank(>33ms)=${framePacing.jankFramesGt33ms}`);
  console.log(`  load: ttfb=${loadMetrics.navigation?.ttfb}ms dcl=${loadMetrics.navigation?.domContentLoaded}ms load=${loadMetrics.navigation?.loadEventEnd}ms fcp=${loadMetrics.firstContentfulPaint}ms longTasks=${longTasks.length} heap=${loadMetrics.memory?.usedJSHeapSize ?? 'n/a'}`);
  console.log(`  inputFeel: pointerdown->0=${inputFeel.pointerdown.fadedToZero} keydown->0=${inputFeel.keydown.fadedToZero}`);
  console.log(`  hudContrast: status=${hudLegibility.contrast.statusTextVsBg} title=${hudLegibility.contrast.titleTextVsScene} (AA=4.5)`);
  console.log(`  resilience: resizeAnyZero=${resilience.resize.anyZeroDimension} rafResumedAfterVisible=${resilience.visibility.rafAdvancedAfterVisible}`);
  console.log(`  gpu: webgl2=${gpu.hasWebGL2} renderer=${gpu.unmaskedRenderer ?? gpu.renderer}`);
  console.log(`  console: gameWarns=${gameWarns.length} errors=${consoleErrors.length} pageErrors=${pageErrors.length}`);
  console.log(`Report: ${reportPath}`);
}

main().catch((err) => {
  console.error('PLAYABILITY CRASH:', err);
  process.exit(2);
});
