/**
 * Item registry — numeric IDs + Wiki name mappings + properties.
 * Items are separate from blocks (items go in inventory, blocks go in world).
 * IDs are sequential starting from 10000 to avoid collision with block IDs.
 */

export const ITEM = {
  // === MATERIALS (10000-10099) ===
  STICK: 10000,
  STRING: 10001,
  FEATHER: 10002,
  FLINT: 10003,
  LEATHER: 10004,
  PAPER: 10005,
  BOOK: 10006,
  CLAY_BALL: 10007,
  BRICK_ITEM: 10008,
  NETHER_WART_ITEM: 10009,
  GUNPOWDER: 10010,
  GLOWSTONE_DUST: 10011,
  REDSTONE_DUST: 10012,
  LAPIS_LAZULI: 10013,
  COAL: 10014,
  CHARCOAL: 10015,
  DIAMOND: 10016,
  EMERALD: 10017,
  IRON_INGOT: 10018,
  GOLD_INGOT: 10019,
  NETHERITE_INGOT: 10020,
  NETHERITE_SCRAP: 10021,
  COPPER_INGOT: 10022,
  RAW_IRON: 10023,
  RAW_GOLD: 10024,
  RAW_COPPER: 10025,
  IRON_NUGGET: 10026,
  GOLD_NUGGET: 10027,
  AMETHYST_SHARD: 10028,
  QUARTZ: 10029,
  RESIN_CLUMP: 10030,
  HONEY_BOTTLE: 10031,
  HONEYCOMB: 10032,
  BONE_MEAL: 10033,
  BONE: 10034,
  SLIMEBALL: 10035,
  BLAZE_ROD: 10036,
  ENDER_PEARL: 10037,
  EYE_OF_ENDER: 10038,
  NETHER_STAR: 10039,
  HEART_OF_THE_SEA: 10040,
  NAUTILUS_SHELL: 10041,
  SHULKER_SHELL: 10042,
  PHANTOM_MEMBRANE: 10043,
  SCUTE: 10044,
  TRIDENT_ITEM: 10045,
  CONDUIT: 10046,
  SPONGE_ITEM: 10047,
  PRISMARINE_CRYSTALS: 10048,
  PRISMARINE_SHARD: 10049,
  COD: 10050,
  SALMON: 10051,
  TROPICAL_FISH: 10052,
  PUFFERFISH: 10053,
  COOKED_COD: 10054,
  COOKED_SALMON: 10055,
  INK_SAC: 10056,
  COPPER_NUGGET: 10057,
  ECHO_SHARD: 10058,
  DISC_FRAGMENT_5: 10059,
  FLOWER: 10060,
  DANDELION: 10061,
  POPPY: 10062,
  BLUE_ORCHID: 10063,
  ALLIUM: 10064,
  AZURE_BLUET: 10065,
  RED_TULIP: 10066,
  ORANGE_TULIP: 10067,
  PINK_TULIP: 10068,
  WHITE_TULIP: 10069,
  OXEYE_DAISY: 10070,
  CORNFLOWER: 10071,
  LILY_OF_THE_VALLEY: 10072,
  WITHER_ROSE: 10073,
  SUNFLOWER: 10074,
  LILAC: 10075,
  ROSE_BUSH: 10076,
  PEONY: 10077,
  CHORUS_FRUIT: 10078,
  POPS_CHORUS: 10079,
  SWEET_BERRIES: 10080,
  GLOW_BERRIES_ITEM: 10081,
  MELON_SLICE: 10082,
  PUMPKIN_SEEDS: 10083,
  MELON_SEEDS: 10084,
  BEETROOT_SEEDS: 10085,
  WHEAT_SEEDS: 10086,
  COCOA_BEANS: 10087,
  SUGAR: 10088,
  CAKE_ITEM: 10089,
  COOKIE: 10090,
  GOLDEN_APPLE: 10091,
  GOLDEN_CARROT: 10092,
  ENCHANTED_GOLDEN_APPLE: 10093,
  ARROW: 10094,
  SPECTRAL_ARROW: 10095,
  TIPPED_ARROW: 10096,
  BOW: 10097,
  CROSSBOW: 10098,
  FISHING_ROD: 10099,

  // === FOOD (10100-10149) ===
  APPLE: 10100,
  BAKED_POTATO: 10101,
  BEETROOT: 10102,
  BEETROOT_SOUP: 10103,
  BREAD: 10104,
  CARROT: 10105,
  COOKED_CHICKEN: 10106,
  COOKED_MUTTON: 10107,
  COOKED_PORKCHOP: 10108,
  COOKED_RABBIT: 10109,
  COOKED_BEEF: 10110,
  COOKIE_ITEM: 10111,
  MUSHROOM_STEW: 10112,
  MUTTON: 10113,
  POISONOUS_POTATO: 10114,
  PORKCHOP: 10115,
  POTATO: 10116,
  PUMPKIN_PIE: 10117,
  RABBIT_STEW: 10118,
  RAW_BEEF: 10119,
  RAW_CHICKEN: 10120,
  RAW_MUTTON: 10121,
  RAW_RABBIT: 10122,
  ROTTEN_FLESH: 10123,
  SPIDER_EYE: 10124,
  STEAK: 10125,
  SUSPICIOUS_STEW: 10126,
  CHORUS_FRUIT_POPPED: 10127,
  DRIED_KELP_ITEM: 10128,
  RABBIT_FOOT: 10129,
  GOLDEN_CARROT_ITEM: 10130,
  GLISTERING_MELON_SLICE: 10131,
  CAKE_SLICE: 10132,

  // === TOOLS (10150-10199) ===
  WOODEN_SWORD: 10150,
  WOODEN_PICKAXE: 10151,
  WOODEN_AXE: 10152,
  WOODEN_SHOVEL: 10153,
  WOODEN_HOE: 10154,
  STONE_SWORD: 10155,
  STONE_PICKAXE: 10156,
  STONE_AXE: 10157,
  STONE_SHOVEL: 10158,
  STONE_HOE: 10159,
  IRON_SWORD: 10160,
  IRON_PICKAXE: 10161,
  IRON_AXE: 10162,
  IRON_SHOVEL: 10163,
  IRON_HOE: 10164,
  DIAMOND_SWORD: 10165,
  DIAMOND_PICKAXE: 10166,
  DIAMOND_AXE: 10167,
  DIAMOND_SHOVEL: 10168,
  DIAMOND_HOE: 10169,
  NETHERITE_SWORD: 10170,
  NETHERITE_PICKAXE: 10171,
  NETHERITE_AXE: 10172,
  NETHERITE_SHOVEL: 10173,
  NETHERITE_HOE: 10174,
  GOLDEN_SWORD: 10175,
  GOLDEN_PICKAXE: 10176,
  GOLDEN_AXE: 10177,
  GOLDEN_SHOVEL: 10178,
  GOLDEN_HOE: 10179,
  SHEARS: 10180,
  FLINT_AND_STEEL: 10181,
  BOW_CHARGED: 10182,
  CROSSBOW_CHARGED: 10183,
  MACE: 10184,
  WOODEN_SPEAR: 10185,
  STONE_SPEAR: 10186,
  IRON_SPEAR: 10187,
  DIAMOND_SPEAR: 10188,
  GOLDEN_SPEAR: 10189,
  NETHERITE_SPEAR: 10190,

  // === ARMOR (10200-10249) ===
  LEATHER_HELMET: 10200,
  LEATHER_CHESTPLATE: 10201,
  LEATHER_LEGGINGS: 10202,
  LEATHER_BOOTS: 10203,
  CHAINMAIL_HELMET: 10204,
  CHAINMAIL_CHESTPLATE: 10205,
  CHAINMAIL_LEGGINGS: 10206,
  CHAINMAIL_BOOTS: 10207,
  IRON_HELMET: 10208,
  IRON_CHESTPLATE: 10209,
  IRON_LEGGINGS: 10210,
  IRON_BOOTS: 10211,
  DIAMOND_HELMET: 10212,
  DIAMOND_CHESTPLATE: 10213,
  DIAMOND_LEGGINGS: 10214,
  DIAMOND_BOOTS: 10215,
  NETHERITE_HELMET: 10216,
  NETHERITE_CHESTPLATE: 10217,
  NETHERITE_LEGGINGS: 10218,
  NETHERITE_BOOTS: 10219,
  GOLDEN_HELMET: 10220,
  GOLDEN_CHESTPLATE: 10221,
  GOLDEN_LEGGINGS: 10222,
  GOLDEN_BOOTS: 10223,
  TURTLE_HELMET: 10224,
  ELYTRA: 10225,
  IRON_HORSE_ARMOR: 10226,
  GOLDEN_HORSE_ARMOR: 10227,
  DIAMOND_HORSE_ARMOR: 10228,
  NETHERITE_HORSE_ARMOR: 10229,
  NAUTILUS_HELMET: 10230,
  NAUTILUS_CHESTPLATE: 10231,
  NAUTILUS_LEGGINGS: 10232,
  NAUTILUS_BOOTS: 10233,

  // === POTIONS (10250-10299) ===
  POTION: 10250,
  SPLASH_POTION: 10251,
  LINGERING_POTION: 10252,
  WATER_BOTTLE: 10253,
  GLASS_BOTTLE: 10254,
  DRAGON_BREATH: 10255,

  // === MISC (10300-10399) ===
  BUCKET: 10300,
  WATER_BUCKET: 10301,
  LAVA_BUCKET: 10302,
  MILK_BUCKET: 10303,
  NAME_TAG: 10304,
  LEAD: 10305,
  SADDLE: 10306,
  TRIDENT: 10307,
  CLOCK: 10308,
  COMPASS: 10309,
  RECOVERY_COMPASS: 10310,
  MAP: 10311,
  EMPTY_MAP: 10312,
  BOOK_AND_QUILL: 10313,
  WRITTEN_BOOK: 10314,
  ENCHANTED_BOOK: 10315,
  KNOWLEDGE_BOOK: 10316,
  COMMAND_BLOCK_MINECART: 10317,
  MINECART: 10318,
  CHEST_MINECART: 10319,
  FURNACE_MINECART: 10320,
  TNT_MINECART: 10321,
  HOPPER_MINECART: 10322,
  BOAT: 10323,
  OAK_BOAT: 10324,
  SPRUCE_BOAT: 10325,
  BIRCH_BOAT: 10326,
  JUNGLE_BOAT: 10327,
  ACACIA_BOAT: 10328,
  DARK_OAK_BOAT: 10329,
  CHERRY_BOAT: 10330,
  BAMBOO_RAFT: 10331,
  MANGROVE_BOAT: 10332,
  OAK_CHEST_BOAT: 10333,
  SPRUCE_CHEST_BOAT: 10334,
  BIRCH_CHEST_BOAT: 10335,
  JUNGLE_CHEST_BOAT: 10336,
  ACACIA_CHEST_BOAT: 10337,
  DARK_OAK_CHEST_BOAT: 10338,
  CHERRY_CHEST_BOAT: 10339,
  BAMBOO_CHEST_RAFT: 10340,
  MANGROVE_CHEST_BOAT: 10341,
  TOTEM_OF_UNDYING: 10342,
  SHIELD: 10343,
  BANNER_ITEM: 10344,
  END_CRYSTAL: 10345,
  END_ROD_ITEM: 10346,
  CHORUS_PLANT_ITEM: 10347,
  BEACON_ITEM: 10348,
  CONDUIT_ITEM: 10349,
  JUKEBOX_ITEM: 10350,
  ANVIL_ITEM: 10351,
  BREWING_STAND_ITEM: 10352,
  CAMPFIRE_ITEM: 10353,
  SOUL_CAMPFIRE_ITEM: 10354,
  BELL_ITEM: 10355,
  SNIFFER_EGG_ITEM: 10356,
  DRAGON_EGG_ITEM: 10357,
  END_PORTAL_FRAME: 10358,
  END_PORTAL_EYE: 10359,
  NETHER_PORTAL: 10360,
  SPAWNER: 10361,
  BARRIER_ITEM: 10362,
  STRUCTURE_BLOCK: 10363,
  STRUCTURE_VOID: 10364,
  COMMAND_BLOCK: 10365,
  CHAIN_COMMAND_BLOCK: 10366,
  REPEATING_COMMAND_BLOCK: 10367,
  DEBUG_STICK: 10368,
  KNOWLEDGE_BOOK_ITEM: 10369,
  GIFT: 10370,
  CHEST_BOAT: 10371,
  OAK_SIGN: 10372,
  SPRUCE_SIGN: 10373,
  BIRCH_SIGN: 10374,
  JUNGLE_SIGN: 10375,
  ACACIA_SIGN: 10376,
  DARK_OAK_SIGN: 10377,
  CHERRY_SIGN: 10378,
  BAMBOO_SIGN: 10379,
  MANGROVE_SIGN: 10380,
  CRIMSON_SIGN: 10381,
  WARPED_SIGN: 10382,
  OAK_HANGING_SIGN: 10383,
  SPRUCE_HANGING_SIGN: 10384,
  BIRCH_HANGING_SIGN: 10385,
  JUNGLE_HANGING_SIGN: 10386,
  ACACIA_HANGING_SIGN: 10387,
  DARK_OAK_HANGING_SIGN: 10388,
  CHERRY_HANGING_SIGN: 10389,
  BAMBOO_HANGING_SIGN: 10390,
  MANGROVE_HANGING_SIGN: 10391,
  CRIMSON_HANGING_SIGN: 10392,
  WARPED_HANGING_SIGN: 10393,

  // === RECORDS (10400-10419) ===
  MUSIC_DISC_13: 10400,
  MUSIC_DISC_CAT: 10401,
  MUSIC_DISC_BLOCKS: 10402,
  MUSIC_DISC_CHIRP: 10403,
  MUSIC_DISC_FAR: 10404,
  MUSIC_DISC_MALL: 10405,
  MUSIC_DISC_MELLOHI: 10406,
  MUSIC_DISC_STAL: 10407,
  MUSIC_DISC_STRAD: 10408,
  MUSIC_DISC_WARD: 10409,
  MUSIC_DISC_11: 10410,
  MUSIC_DISC_WAIT: 10411,
  MUSIC_DISC_OTHERSIDE: 10412,
  MUSIC_DISC_5: 10413,
  MUSIC_DISC_PIGSTEP: 10414,
  MUSIC_DISC_RELIC: 10415,
  MUSIC_DISC_CREATOR: 10416,
  MUSIC_DISC_CREATOR_MUSIC_BOX: 10417,
  MUSIC_DISC_PRECIPICE: 10418,
  MUSIC_DISC_BOUNCE: 10419,

  // === 26.2 ADDITIONS (10420-10429) ===
  SULFUR_CUBE_SPAWN_EGG: 10420,
  BUCKET_OF_SULFUR_CUBE: 10421,
  GOLDEN_DANDELION: 10422,

  // === 1.21.11 ADDITIONS (10430-10449) ===
  COPPER_NAUTILUS_ARMOR: 10430,
  IRON_NAUTILUS_ARMOR: 10431,
  GOLDEN_NAUTILUS_ARMOR: 10432,
  DIAMOND_NAUTILUS_ARMOR: 10433,
  NETHERITE_NAUTILUS_ARMOR: 10434,

  // === SPAWN EGGS (10500-10599) ===
  SPAWN_EGG_ZOMBIE: 10500,
  SPAWN_EGG_SKELETON: 10501,
  SPAWN_EGG_CREEPER: 10502,
  SPAWN_EGG_SPIDER: 10503,
  SPAWN_EGG_CAVE_SPIDER: 10504,
  SPAWN_EGG_ENDERMAN: 10505,
  SPAWN_EGG_WITCH: 10506,
  SPAWN_EGG_BLAZE: 10507,
  SPAWN_EGG_GHAST: 10508,
  SPAWN_EGG_SLIME: 10509,
  SPAWN_EGG_ZOMBIE_PIGLIN: 10510,
  SPAWN_EGG_PIGLIN: 10511,
  SPAWN_EGG_PIGLIN_BRUTE: 10512,
  SPAWN_EGG_HOGLIN: 10513,
  SPAWN_EGG_ZOGLIN: 10514,
  SPAWN_EGG_STRIDER: 10515,
  SPAWN_EGG_PHANTOM: 10516,
  SPAWN_EGG_DROWNED: 10517,
  SPAWN_EGG_HUSK: 10518,
  SPAWN_EGG_STRAY: 10519,
  SPAWN_EGG_VEX: 10520,
  SPAWN_EGG_EVOKER: 10521,
  SPAWN_EGG_VINDICATOR: 10522,
  SPAWN_EGG_PILLAGER: 10523,
  SPAWN_EGG_RAVAGER: 10524,
  SPAWN_EGG_WARDEN: 10525,
  SPAWN_EGG_BREEZE: 10526,
  SPAWN_EGG_BOGGED: 10527,
  SPAWN_EGG_COW: 10528,
  SPAWN_EGG_PIG: 10529,
  SPAWN_EGG_SHEEP: 10530,
  SPAWN_EGG_CHICKEN: 10531,
  SPAWN_EGG_RABBIT: 10532,
  SPAWN_EGG_HORSE: 10533,
  SPAWN_EGG_DONKEY: 10534,
  SPAWN_EGG_MULE: 10535,
  SPAWN_EGG_LLAMA: 10536,
  SPAWN_EGG_CAT: 10537,
  SPAWN_EGG_WOLF: 10538,
  SPAWN_EGG_BEE: 10539,
  SPAWN_EGG_FOX: 10540,
  SPAWN_EGG_AXOLOTL: 10541,
  SPAWN_EGG_DOLPHIN: 10542,
  SPAWN_EGG_TURTLE: 10543,
  SPAWN_EGG_PANDA: 10544,
  SPAWN_EGG_GOAT: 10545,
  SPAWN_EGG_CAMEL: 10546,
  SPAWN_EGG_ARMADILLO: 10547,
  SPAWN_EGG_SNIFFER: 10548,
  SPAWN_EGG_FROG: 10549,
  SPAWN_EGG_TADPOLE: 10550,
  SPAWN_EGG_ALLAY: 10551,
  SPAWN_EGG_VILLAGER: 10552,
  SPAWN_EGG_IRON_GOLEM: 10553,
  SPAWN_EGG_SNOW_GOLEM: 10554,
  SPAWN_EGG_ENDER_DRAGON: 10555,
  SPAWN_EGG_WITHER: 10556,
  SPAWN_EGG_SQUID: 10557,
  SPAWN_EGG_GLOW_SQUID: 10558,
  SPAWN_EGG_BAT: 10559,
  SPAWN_EGG_OCELOT: 10560,
  SPAWN_EGG_PUFFERFISH: 10561,
  SPAWN_EGG_COD: 10562,
  SPAWN_EGG_SALMON: 10563,
  SPAWN_EGG_TROPICAL_FISH: 10564,
  SPAWN_EGG_GUARDIAN: 10565,
  SPAWN_EGG_ELDER_GUARDIAN: 10566,
  SPAWN_EGG_MAGMA_CUBE: 10567,
  SPAWN_EGG_SHULKER: 10568,
  SPAWN_EGG_SILVERFISH: 10569,
  SPAWN_EGG_ENDERMITE: 10570,
  SPAWN_EGG_GIANT: 10571,
  SPAWN_EGG_ZOMBIE_HORSE: 10572,
  SPAWN_EGG_SKELETON_HORSE: 10573,
  SPAWN_EGG_ZOMBIE_VILLAGER: 10574,
  SPAWN_EGG_PARROT: 10575,
  SPAWN_EGG_WANDERING_TRADER: 10576,
  SPAWN_EGG_TRADER_LLAMA: 10577,
  SPAWN_EGG_CREEPER_CHARGED: 10578,
  SPAWN_EGG_SKELETON_TRAP: 10579,
  SPAWN_EGG_DROWNED_TRIDENT: 10580,
  SPAWN_EGG_PIGLIN_BRUTE_GOLD: 10581,

  // === DYES (10600-10619) ===
  RED_DYE: 10600,
  ORANGE_DYE: 10601,
  YELLOW_DYE: 10602,
  LIME_DYE: 10603,
  GREEN_DYE: 10604,
  CYAN_DYE: 10605,
  LIGHT_BLUE_DYE: 10606,
  BLUE_DYE: 10607,
  PURPLE_DYE: 10608,
  MAGENTA_DYE: 10609,
  PINK_DYE: 10610,
  WHITE_DYE: 10611,
  LIGHT_GRAY_DYE: 10612,
  GRAY_DYE: 10613,
  BROWN_DYE: 10614,
  BLACK_DYE: 10615,

  // === INGREDIENTS & FOOD EXTRAS (10620-10649) ===
  BOWL: 10620,
  BROWN_MUSHROOM: 10621,
  RED_MUSHROOM: 10622,
  EGG: 10623,
  BLAZE_POWDER: 10624,
  GHAST_TEAR: 10626,
  ENDER_EYE: 10627,
  POPPED_CHORUS: 10629,
  WHEAT: 10630,

  // === OVERWORLD ORE ITEMS (10631-10639) ===
  IRON_ORE: 10631,
  GOLD_ORE: 10632,
  COPPER_ORE: 10633,
  DIAMOND_ORE: 10634,
  EMERALD_ORE: 10635,
  LAPIS_ORE: 10636,
  REDSTONE_ORE: 10637,
  DEEPSLATE_IRON_ORE: 10638,
  DEEPSLATE_GOLD_ORE: 10639,
  DEEPSLATE_COPPER_ORE: 10640,
  DEEPSLATE_DIAMOND_ORE: 10641,

  // === BLOCK ITEMS (10650-10669) ===
  TORCH: 10650,
  SOUL_TORCH: 10651,
  REDSTONE_TORCH: 10652,
  REDSTONE_BLOCK: 10653,
  GLASS_PANE: 10654,
  JUKEBOX: 10655,
  OAK_BED: 10656,
  OAK_BUTTON: 10657,

  // === EXTRA ORE ITEMS (10670-10684) ===
  NETHER_BRICK_ITEM: 10683,
  KELP: 10684,

  // === SAPLING ITEMS (10690-10699) ===
  SPRUCE_SAPLING: 10691,
  BIRCH_SAPLING: 10692,
  JUNGLE_SAPLING: 10693,
  ACACIA_SAPLING: 10694,
  DARK_OAK_SAPLING: 10695,

  // === WOOD VARIANTS (10700-10709) ===
  SPRUCE_WOOD: 10701,
  BIRCH_WOOD: 10702,
  JUNGLE_WOOD: 10703,
  ACACIA_WOOD: 10704,
  DARK_OAK_WOOD: 10705,
  MANGROVE_WOOD: 10706,

  // === RAW FOOD (10710-10719) ===
  RAW_PORKCHOP: 10710,

  // === MCE MOB ITEMS (10720-10749) ===
  // Chickens
  MCE_CHICKEN: 10720,
  MCE_AMBER_CHICKEN: 10721,
  MCE_MIDNIGHT_CHICKEN: 10722,
  MCE_STORMY_CHICKEN: 10723,
  MCE_BRONZED_CHICKEN: 10724,
  MCECLUCKSHROOM: 10725,
  MCE_FANCY_CHICKEN: 10726,
  MCE_SKEWBALD_CHICKEN: 10727,
  MCE_GOLD_CRESTED_CHICKEN: 10728,
  // Cows
  MCE_COW: 10729,
  MCE_ALBINO_COW: 10730,
  MCE_ASHEN_COW: 10731,
  MCE_SUNSET_COW: 10732,
  MCE_COOKIE_COW: 10733,
  MCE_WOOLY_COW: 10734,
  MCE_PINTO_COW: 10735,
  MCE_MOOBLOOM: 10736,
  MCE_MOOLIP: 10737,
  MCE_CREAM_COW: 10738,
  MCE_DAIRY_COW: 10739,
  MCE_UMBRA_COW: 10740,
  // Pigs
  MCE_PIG: 10741,
  MCE_PALE_PIG: 10742,
  MCE_PIEBALD_PIG: 10743,
  MCE_SPOTTED_PIG: 10744,
  MCE_PINK_FOOTED_PIG: 10745,
  MCE_MUDDY_PIG: 10746,
  MCE_MOTTLED_PIG: 10747,
  MCE_SOOTY_PIG: 10748,
  MCE_DRIED_MUDDY_PIG: 10749,
  // Sheep
  MCE_WHITE_SHEEP: 10750,
  MCE_FLECKED_SHEEP: 10751,
  MCE_INKY_SHEEP: 10752,
  MCE_ROCKY_SHEEP: 10753,
  MCE_PATCHED_SHEEP: 10754,
  MCE_HORNED_SHEEP: 10755,
  MCE_RAINBOW_SHEEP: 10756,
  MCE_FUZZY_SHEEP: 10757,
  MCE_LONG_NOSE_SHEEP: 10758,
  // Rabbits
  MCE_BOLD_STRIPED_RABBIT: 10759,
  MCE_FRECKLED_RABBIT: 10760,
  MCE_HARELEQUIN_RABBIT: 10761,
  MCE_JUMBO_RABBIT: 10762,
  MCE_MUDDY_FOOT_RABBIT: 10763,
  MCE_VESTED_RABBIT: 10764,
  // Golems & Hostile
  MCE_FURNACE_GOLEM: 10765,
  MCE_MELON_GOLEM: 10766,
  MCE_SKELETON_WOLF: 10767,
  MCE_BONE_SPIDER: 10768,
  MCE_BOULDERING_ZOMBIE: 10769,
  MCE_LOBBER_ZOMBIE: 10770,
  MCE_VILER_WITCH: 10771,
  // Other
  MCE_GLOW_SQUID: 10772,
  MCE_JOLLY_LLAMA: 10773,
  MCE_MOB_OF_ME: 10774,
  MCE_TROPICAL_SLIME: 10775,

  // === MCE EXCLUSIVE ITEMS (10780-10799) ===
  MCE_ADVENTURE_CRYSTAL_COMMON: 10780,
  MCE_ADVENTURE_CRYSTAL_UNCOMMON: 10781,
  MCE_ADVENTURE_CRYSTAL_RARE: 10782,
  MCE_ADVENTURE_CRYSTAL_EPIC: 10783,
  MCE_ADVENTURE_CRYSTAL_LEGENDARY: 10784,
  MCE_BUCKET_OF_MUD: 10785,
  MCE_FANCY_FEATHER: 10786,
  MCE_HORN: 10787,
  MCE_RUBY: 10788,
  MCE_RUBY_BLOCK: 10789,
  // MCE Nature
  MCE_BUTTERCUP: 10790,
  MCE_PINK_DAISY: 10791,
  // MCE Construction
  MCE_RAINBOW_CARPET: 10792,
  MCE_RAINBOW_BED: 10793,
  MCE_RAINBOW_WOOL: 10794,
  MCE_MUD: 10795,

  // === BLOCK-AS-ITEM (10800-10899) — blocks collectible via tappables ===
  DIRT: 10800,
  GRASS: 10801,
  FERN: 10802,
  LILY_PAD: 10803,
  CARVED_PUMPKIN: 10804,
  COBBLESTONE: 10805,
  GRAVEL: 10806,
  MYCELIUM: 10807,
  SAND: 10808,
  REDSTONE: 10809,
  OAK_SAPLING: 10810,
  OAK_PLANKS: 10811,
  ACACIA_PLANKS: 10812,
  DARK_OAK_PLANKS: 10813,
  BIRCH_LOG: 10814,
  OAK_LOG: 10815,
  SPRUCE_LOG: 10816,
  BIRCH_LEAVES: 10817,
  OAK_LEAVES: 10818,
  SPRUCE_LEAVES: 10819,
  BRICK: 10820,
  CLAY: 10821,
  COBBLESTONE_STAIRS: 10822,
  COBBLESTONE_WALL: 10823,
  GLASS: 10824,
  IRON_BARS: 10825,
  NOTE_BLOCK: 10826,
  OAK_DOOR: 10827,
  OAK_FENCE: 10828,
  OAK_FENCE_GATE: 10829,
  OAK_PRESSURE_PLATE: 10830,
  OAK_STAIRS: 10831,
  OAK_SLAB: 10832,
  POLISHED_ANDESITE: 10833,
  POLISHED_DIORITE: 10834,
  POLISHED_GRANITE: 10835,
  POWERED_RAIL: 10836,
  STONE_BRICK: 10837,
  TNT: 10838,
  ANDESITE: 10839,
  DIORITE: 10840,
  GRANITE: 10841,
  STONE: 10842,
  STONE_BRICKS: 10843,
  POLISHED_ANDESITE_SLAB: 10844,
  POLISHED_ANDESITE_STAIRS: 10845,
  POLISHED_DIORITE_SLAB: 10846,
  POLISHED_DIORITE_STAIRS: 10847,
  POLISHED_GRANITE_SLAB: 10848,
  POLISHED_GRANITE_STAIRS: 10849,
  RAIL: 10850,
  REDSTONE_LAMP: 10851,
  REDSTONE_REPEATER: 10852,
  COBWEB: 10853,
  FLOWER_POT: 10854,
  IRON_DOOR: 10855,
  LEVER: 10856,
} as const;

export type ItemId = (typeof ITEM)[keyof typeof ITEM];

/**
 * Item properties for gameplay mechanics.
 */
export interface ItemProperties {
  id: ItemId;
  name: string;
  displayName: string;
  maxStackSize: number;
  durability?: number; // for tools/armor
  damage?: number;    // for weapons
  miningSpeed?: number; // for tools (multiplier)
  miningLevel?: number; // 0=hand, 1=wood, 2=stone, 3=iron, 4=diamond, 5=netherite
  armorPoints?: number; // for armor
  armorToughness?: number; // for armor
  enchantability?: number; // for tools/armor
  repairMaterial?: ItemId; // what repairs this item
  foodPoints?: number; // for food
  saturation?: number; // for food
  category: 'material' | 'tool' | 'weapon' | 'armor' | 'food' | 'potion' | 'misc' | 'spawn_egg' | 'record';
}

export const ITEM_PROPERTIES: Record<number, ItemProperties> = {
  // === MATERIALS ===
  [ITEM.STICK]: {
    id: ITEM.STICK,
    name: 'stick',
    displayName: 'Stick',
    maxStackSize: 64,
    category: 'material',
  },
  [ITEM.STRING]: {
    id: ITEM.STRING,
    name: 'string',
    displayName: 'String',
    maxStackSize: 64,
    category: 'material',
  },
  [ITEM.FEATHER]: {
    id: ITEM.FEATHER,
    name: 'feather',
    displayName: 'Feather',
    maxStackSize: 64,
    category: 'material',
  },
  [ITEM.FLINT]: {
    id: ITEM.FLINT,
    name: 'flint',
    displayName: 'Flint',
    maxStackSize: 64,
    category: 'material',
  },
  [ITEM.LEATHER]: {
    id: ITEM.LEATHER,
    name: 'leather',
    displayName: 'Leather',
    maxStackSize: 64,
    category: 'material',
  },
  [ITEM.PAPER]: {
    id: ITEM.PAPER,
    name: 'paper',
    displayName: 'Paper',
    maxStackSize: 64,
    category: 'material',
  },
  [ITEM.BOOK]: {
    id: ITEM.BOOK,
    name: 'book',
    displayName: 'Book',
    maxStackSize: 64,
    category: 'material',
  },
  [ITEM.CLAY_BALL]: {
    id: ITEM.CLAY_BALL,
    name: 'clay_ball',
    displayName: 'Clay Ball',
    maxStackSize: 64,
    category: 'material',
  },
  [ITEM.BRICK_ITEM]: {
    id: ITEM.BRICK_ITEM,
    name: 'brick',
    displayName: 'Brick',
    maxStackSize: 64,
    category: 'material',
  },
  [ITEM.COAL]: {
    id: ITEM.COAL,
    name: 'coal',
    displayName: 'Coal',
    maxStackSize: 64,
    category: 'material',
  },
  [ITEM.CHARCOAL]: {
    id: ITEM.CHARCOAL,
    name: 'charcoal',
    displayName: 'Charcoal',
    maxStackSize: 64,
    category: 'material',
  },
  [ITEM.IRON_INGOT]: {
    id: ITEM.IRON_INGOT,
    name: 'iron_ingot',
    displayName: 'Iron Ingot',
    maxStackSize: 64,
    category: 'material',
  },
  [ITEM.GOLD_INGOT]: {
    id: ITEM.GOLD_INGOT,
    name: 'gold_ingot',
    displayName: 'Gold Ingot',
    maxStackSize: 64,
    category: 'material',
  },
  [ITEM.DIAMOND]: {
    id: ITEM.DIAMOND,
    name: 'diamond',
    displayName: 'Diamond',
    maxStackSize: 64,
    category: 'material',
  },
  [ITEM.EMERALD]: {
    id: ITEM.EMERALD,
    name: 'emerald',
    displayName: 'Emerald',
    maxStackSize: 64,
    category: 'material',
  },
  [ITEM.NETHERITE_INGOT]: {
    id: ITEM.NETHERITE_INGOT,
    name: 'netherite_ingot',
    displayName: 'Netherite Ingot',
    maxStackSize: 64,
    category: 'material',
  },
  [ITEM.NETHERITE_SCRAP]: {
    id: ITEM.NETHERITE_SCRAP,
    name: 'netherite_scrap',
    displayName: 'Netherite Scrap',
    maxStackSize: 64,
    category: 'material',
  },
  [ITEM.REDSTONE_DUST]: {
    id: ITEM.REDSTONE_DUST,
    name: 'redstone',
    displayName: 'Redstone Dust',
    maxStackSize: 64,
    category: 'material',
  },
  [ITEM.LAPIS_LAZULI]: {
    id: ITEM.LAPIS_LAZULI,
    name: 'lapis_lazuli',
    displayName: 'Lapis Lazuli',
    maxStackSize: 64,
    category: 'material',
  },
  [ITEM.GLOWSTONE_DUST]: {
    id: ITEM.GLOWSTONE_DUST,
    name: 'glowstone_dust',
    displayName: 'Glowstone Dust',
    maxStackSize: 64,
    category: 'material',
  },
  [ITEM.BLAZE_ROD]: {
    id: ITEM.BLAZE_ROD,
    name: 'blaze_rod',
    displayName: 'Blaze Rod',
    maxStackSize: 64,
    category: 'material',
  },
  [ITEM.ENDER_PEARL]: {
    id: ITEM.ENDER_PEARL,
    name: 'ender_pearl',
    displayName: 'Ender Pearl',
    maxStackSize: 16,
    category: 'material',
  },
  [ITEM.EYE_OF_ENDER]: {
    id: ITEM.EYE_OF_ENDER,
    name: 'ender_eye',
    displayName: 'Eye of Ender',
    maxStackSize: 64,
    category: 'material',
  },
  [ITEM.BONE]: {
    id: ITEM.BONE,
    name: 'bone',
    displayName: 'Bone',
    maxStackSize: 64,
    category: 'material',
  },
  [ITEM.BONE_MEAL]: {
    id: ITEM.BONE_MEAL,
    name: 'bone_meal',
    displayName: 'Bone Meal',
    maxStackSize: 64,
    category: 'material',
  },
  [ITEM.SLIMEBALL]: {
    id: ITEM.SLIMEBALL,
    name: 'slimeball',
    displayName: 'Slimeball',
    maxStackSize: 64,
    category: 'material',
  },
  [ITEM.PRISMARINE_SHARD]: {
    id: ITEM.PRISMARINE_SHARD,
    name: 'prismarine_shard',
    displayName: 'Prismarine Shard',
    maxStackSize: 64,
    category: 'material',
  },
  [ITEM.PRISMARINE_CRYSTALS]: {
    id: ITEM.PRISMARINE_CRYSTALS,
    name: 'prismarine_crystals',
    displayName: 'Prismarine Crystals',
    maxStackSize: 64,
    category: 'material',
  },

  // === TOOLS ===
  [ITEM.WOODEN_PICKAXE]: {
    id: ITEM.WOODEN_PICKAXE,
    name: 'wooden_pickaxe',
    displayName: 'Wooden Pickaxe',
    maxStackSize: 1,
    durability: 59,
    miningSpeed: 2,
    miningLevel: 1,
    enchantability: 15,
    category: 'tool',
  },
  [ITEM.STONE_PICKAXE]: {
    id: ITEM.STONE_PICKAXE,
    name: 'stone_pickaxe',
    displayName: 'Stone Pickaxe',
    maxStackSize: 1,
    durability: 131,
    miningSpeed: 4,
    miningLevel: 2,
    enchantability: 5,
    category: 'tool',
  },
  [ITEM.IRON_PICKAXE]: {
    id: ITEM.IRON_PICKAXE,
    name: 'iron_pickaxe',
    displayName: 'Iron Pickaxe',
    maxStackSize: 1,
    durability: 250,
    miningSpeed: 6,
    miningLevel: 3,
    enchantability: 9,
    category: 'tool',
  },
  [ITEM.DIAMOND_PICKAXE]: {
    id: ITEM.DIAMOND_PICKAXE,
    name: 'diamond_pickaxe',
    displayName: 'Diamond Pickaxe',
    maxStackSize: 1,
    durability: 1561,
    miningSpeed: 8,
    miningLevel: 4,
    enchantability: 10,
    category: 'tool',
  },
  [ITEM.NETHERITE_PICKAXE]: {
    id: ITEM.NETHERITE_PICKAXE,
    name: 'netherite_pickaxe',
    displayName: 'Netherite Pickaxe',
    maxStackSize: 1,
    durability: 2031,
    miningSpeed: 9,
    miningLevel: 5,
    enchantability: 15,
    category: 'tool',
  },
  [ITEM.GOLDEN_PICKAXE]: {
    id: ITEM.GOLDEN_PICKAXE,
    name: 'golden_pickaxe',
    displayName: 'Golden Pickaxe',
    maxStackSize: 1,
    durability: 32,
    miningSpeed: 12,
    miningLevel: 1,
    enchantability: 25,
    category: 'tool',
  },
  [ITEM.WOODEN_AXE]: {
    id: ITEM.WOODEN_AXE,
    name: 'wooden_axe',
    displayName: 'Wooden Axe',
    maxStackSize: 1,
    durability: 59,
    miningSpeed: 2,
    miningLevel: 1,
    damage: 7,
    enchantability: 15,
    category: 'tool',
  },
  [ITEM.STONE_AXE]: {
    id: ITEM.STONE_AXE,
    name: 'stone_axe',
    displayName: 'Stone Axe',
    maxStackSize: 1,
    durability: 131,
    miningSpeed: 4,
    miningLevel: 2,
    damage: 9,
    enchantability: 5,
    category: 'tool',
  },
  [ITEM.IRON_AXE]: {
    id: ITEM.IRON_AXE,
    name: 'iron_axe',
    displayName: 'Iron Axe',
    maxStackSize: 1,
    durability: 250,
    miningSpeed: 6,
    miningLevel: 3,
    damage: 9,
    enchantability: 9,
    category: 'tool',
  },
  [ITEM.DIAMOND_AXE]: {
    id: ITEM.DIAMOND_AXE,
    name: 'diamond_axe',
    displayName: 'Diamond Axe',
    maxStackSize: 1,
    durability: 1561,
    miningSpeed: 8,
    miningLevel: 4,
    damage: 9,
    enchantability: 10,
    category: 'tool',
  },
  [ITEM.NETHERITE_AXE]: {
    id: ITEM.NETHERITE_AXE,
    name: 'netherite_axe',
    displayName: 'Netherite Axe',
    maxStackSize: 1,
    durability: 2031,
    miningSpeed: 9,
    miningLevel: 5,
    damage: 10,
    enchantability: 15,
    category: 'tool',
  },
  [ITEM.WOODEN_SHOVEL]: {
    id: ITEM.WOODEN_SHOVEL,
    name: 'wooden_shovel',
    displayName: 'Wooden Shovel',
    maxStackSize: 1,
    durability: 59,
    miningSpeed: 2,
    miningLevel: 1,
    enchantability: 15,
    category: 'tool',
  },
  [ITEM.STONE_SHOVEL]: {
    id: ITEM.STONE_SHOVEL,
    name: 'stone_shovel',
    displayName: 'Stone Shovel',
    maxStackSize: 1,
    durability: 131,
    miningSpeed: 4,
    miningLevel: 2,
    enchantability: 5,
    category: 'tool',
  },
  [ITEM.IRON_SHOVEL]: {
    id: ITEM.IRON_SHOVEL,
    name: 'iron_shovel',
    displayName: 'Iron Shovel',
    maxStackSize: 1,
    durability: 250,
    miningSpeed: 6,
    miningLevel: 3,
    enchantability: 9,
    category: 'tool',
  },
  [ITEM.DIAMOND_SHOVEL]: {
    id: ITEM.DIAMOND_SHOVEL,
    name: 'diamond_shovel',
    displayName: 'Diamond Shovel',
    maxStackSize: 1,
    durability: 1561,
    miningSpeed: 8,
    miningLevel: 4,
    enchantability: 10,
    category: 'tool',
  },
  [ITEM.NETHERITE_SHOVEL]: {
    id: ITEM.NETHERITE_SHOVEL,
    name: 'netherite_shovel',
    displayName: 'Netherite Shovel',
    maxStackSize: 1,
    durability: 2031,
    miningSpeed: 9,
    miningLevel: 5,
    enchantability: 15,
    category: 'tool',
  },
  [ITEM.WOODEN_HOE]: {
    id: ITEM.WOODEN_HOE,
    name: 'wooden_hoe',
    displayName: 'Wooden Hoe',
    maxStackSize: 1,
    durability: 59,
    miningSpeed: 2,
    miningLevel: 1,
    enchantability: 15,
    category: 'tool',
  },
  [ITEM.STONE_HOE]: {
    id: ITEM.STONE_HOE,
    name: 'stone_hoe',
    displayName: 'Stone Hoe',
    maxStackSize: 1,
    durability: 131,
    miningSpeed: 4,
    miningLevel: 2,
    enchantability: 5,
    category: 'tool',
  },
  [ITEM.IRON_HOE]: {
    id: ITEM.IRON_HOE,
    name: 'iron_hoe',
    displayName: 'Iron Hoe',
    maxStackSize: 1,
    durability: 250,
    miningSpeed: 6,
    miningLevel: 3,
    enchantability: 9,
    category: 'tool',
  },
  [ITEM.DIAMOND_HOE]: {
    id: ITEM.DIAMOND_HOE,
    name: 'diamond_hoe',
    displayName: 'Diamond Hoe',
    maxStackSize: 1,
    durability: 1561,
    miningSpeed: 8,
    miningLevel: 4,
    enchantability: 10,
    category: 'tool',
  },
  [ITEM.NETHERITE_HOE]: {
    id: ITEM.NETHERITE_HOE,
    name: 'netherite_hoe',
    displayName: 'Netherite Hoe',
    maxStackSize: 1,
    durability: 2031,
    miningSpeed: 9,
    miningLevel: 5,
    enchantability: 15,
    category: 'tool',
  },
  [ITEM.SHEARS]: {
    id: ITEM.SHEARS,
    name: 'shears',
    displayName: 'Shears',
    maxStackSize: 1,
    durability: 238,
    miningSpeed: 1.5, // wiki-source: https://minecraft.wiki/w/Shears
    miningLevel: 0,
    enchantability: 30,
    category: 'tool',
  },
  [ITEM.FLINT_AND_STEEL]: {
    id: ITEM.FLINT_AND_STEEL,
    name: 'flint_and_steel',
    displayName: 'Flint and Steel',
    maxStackSize: 1,
    durability: 64,
    category: 'tool',
  },

  // === WEAPONS ===
  [ITEM.WOODEN_SWORD]: {
    id: ITEM.WOODEN_SWORD,
    name: 'wooden_sword',
    displayName: 'Wooden Sword',
    maxStackSize: 1,
    durability: 59,
    damage: 4,
    miningSpeed: 1.5,
    enchantability: 15,
    category: 'weapon',
  },
  [ITEM.STONE_SWORD]: {
    id: ITEM.STONE_SWORD,
    name: 'stone_sword',
    displayName: 'Stone Sword',
    maxStackSize: 1,
    durability: 131,
    damage: 5,
    miningSpeed: 1.5,
    enchantability: 5,
    category: 'weapon',
  },
  [ITEM.IRON_SWORD]: {
    id: ITEM.IRON_SWORD,
    name: 'iron_sword',
    displayName: 'Iron Sword',
    maxStackSize: 1,
    durability: 250,
    damage: 6,
    miningSpeed: 1.5,
    enchantability: 9,
    category: 'weapon',
  },
  [ITEM.DIAMOND_SWORD]: {
    id: ITEM.DIAMOND_SWORD,
    name: 'diamond_sword',
    displayName: 'Diamond Sword',
    maxStackSize: 1,
    durability: 1561,
    damage: 7,
    miningSpeed: 1.5,
    enchantability: 10,
    category: 'weapon',
  },
  [ITEM.NETHERITE_SWORD]: {
    id: ITEM.NETHERITE_SWORD,
    name: 'netherite_sword',
    displayName: 'Netherite Sword',
    maxStackSize: 1,
    durability: 2031,
    damage: 8,
    miningSpeed: 1.5,
    enchantability: 15,
    category: 'weapon',
  },
  [ITEM.GOLDEN_SWORD]: {
    id: ITEM.GOLDEN_SWORD,
    name: 'golden_sword',
    displayName: 'Golden Sword',
    maxStackSize: 1,
    durability: 32,
    damage: 4,
    miningSpeed: 1.5,
    enchantability: 25,
    category: 'weapon',
  },
  [ITEM.BOW]: {
    id: ITEM.BOW,
    name: 'bow',
    displayName: 'Bow',
    maxStackSize: 1,
    durability: 384,
    category: 'weapon',
  },
  [ITEM.CROSSBOW]: {
    id: ITEM.CROSSBOW,
    name: 'crossbow',
    displayName: 'Crossbow',
    maxStackSize: 1,
    durability: 465,
    category: 'weapon',
  },
  [ITEM.TRIDENT]: {
    id: ITEM.TRIDENT,
    name: 'trident',
    displayName: 'Trident',
    maxStackSize: 1,
    durability: 250,
    damage: 9,
    category: 'weapon',
  },
  [ITEM.MACE]: {
    id: ITEM.MACE,
    name: 'mace',
    displayName: 'Mace',
    maxStackSize: 1,
    durability: 500,
    damage: 6,
    category: 'weapon',
  },
  [ITEM.SHIELD]: {
    id: ITEM.SHIELD,
    name: 'shield',
    displayName: 'Shield',
    maxStackSize: 1,
    durability: 336,
    category: 'weapon',
  },

  // === ARMOR ===
  [ITEM.LEATHER_HELMET]: {
    id: ITEM.LEATHER_HELMET,
    name: 'leather_helmet',
    displayName: 'Leather Cap',
    maxStackSize: 1,
    durability: 55,
    armorPoints: 1,
    enchantability: 15,
    category: 'armor',
  },
  [ITEM.LEATHER_CHESTPLATE]: {
    id: ITEM.LEATHER_CHESTPLATE,
    name: 'leather_chestplate',
    displayName: 'Leather Tunic',
    maxStackSize: 1,
    durability: 80,
    armorPoints: 3,
    enchantability: 15,
    category: 'armor',
  },
  [ITEM.LEATHER_LEGGINGS]: {
    id: ITEM.LEATHER_LEGGINGS,
    name: 'leather_leggings',
    displayName: 'Leather Pants',
    maxStackSize: 1,
    durability: 75,
    armorPoints: 2,
    enchantability: 15,
    category: 'armor',
  },
  [ITEM.LEATHER_BOOTS]: {
    id: ITEM.LEATHER_BOOTS,
    name: 'leather_boots',
    displayName: 'Leather Boots',
    maxStackSize: 1,
    durability: 65,
    armorPoints: 1,
    enchantability: 15,
    category: 'armor',
  },
  [ITEM.IRON_HELMET]: {
    id: ITEM.IRON_HELMET,
    name: 'iron_helmet',
    displayName: 'Iron Helmet',
    maxStackSize: 1,
    durability: 165,
    armorPoints: 2,
    enchantability: 9,
    category: 'armor',
  },
  [ITEM.IRON_CHESTPLATE]: {
    id: ITEM.IRON_CHESTPLATE,
    name: 'iron_chestplate',
    displayName: 'Iron Chestplate',
    maxStackSize: 1,
    durability: 240,
    armorPoints: 6,
    enchantability: 9,
    category: 'armor',
  },
  [ITEM.IRON_LEGGINGS]: {
    id: ITEM.IRON_LEGGINGS,
    name: 'iron_leggings',
    displayName: 'Iron Leggings',
    maxStackSize: 1,
    durability: 225,
    armorPoints: 5,
    enchantability: 9,
    category: 'armor',
  },
  [ITEM.IRON_BOOTS]: {
    id: ITEM.IRON_BOOTS,
    name: 'iron_boots',
    displayName: 'Iron Boots',
    maxStackSize: 1,
    durability: 195,
    armorPoints: 2,
    enchantability: 9,
    category: 'armor',
  },
  [ITEM.DIAMOND_HELMET]: {
    id: ITEM.DIAMOND_HELMET,
    name: 'diamond_helmet',
    displayName: 'Diamond Helmet',
    maxStackSize: 1,
    durability: 363,
    armorPoints: 3,
    armorToughness: 2,
    enchantability: 10,
    category: 'armor',
  },
  [ITEM.DIAMOND_CHESTPLATE]: {
    id: ITEM.DIAMOND_CHESTPLATE,
    name: 'diamond_chestplate',
    displayName: 'Diamond Chestplate',
    maxStackSize: 1,
    durability: 528,
    armorPoints: 8,
    armorToughness: 2,
    enchantability: 10,
    category: 'armor',
  },
  [ITEM.DIAMOND_LEGGINGS]: {
    id: ITEM.DIAMOND_LEGGINGS,
    name: 'diamond_leggings',
    displayName: 'Diamond Leggings',
    maxStackSize: 1,
    durability: 495,
    armorPoints: 6,
    armorToughness: 2,
    enchantability: 10,
    category: 'armor',
  },
  [ITEM.DIAMOND_BOOTS]: {
    id: ITEM.DIAMOND_BOOTS,
    name: 'diamond_boots',
    displayName: 'Diamond Boots',
    maxStackSize: 1,
    durability: 429,
    armorPoints: 3,
    armorToughness: 2,
    enchantability: 10,
    category: 'armor',
  },
  [ITEM.NETHERITE_HELMET]: {
    id: ITEM.NETHERITE_HELMET,
    name: 'netherite_helmet',
    displayName: 'Netherite Helmet',
    maxStackSize: 1,
    durability: 407,
    armorPoints: 3,
    armorToughness: 3,
    enchantability: 15,
    category: 'armor',
  },
  [ITEM.NETHERITE_CHESTPLATE]: {
    id: ITEM.NETHERITE_CHESTPLATE,
    name: 'netherite_chestplate',
    displayName: 'Netherite Chestplate',
    maxStackSize: 1,
    durability: 592,
    armorPoints: 8,
    armorToughness: 3,
    enchantability: 15,
    category: 'armor',
  },
  [ITEM.NETHERITE_LEGGINGS]: {
    id: ITEM.NETHERITE_LEGGINGS,
    name: 'netherite_leggings',
    displayName: 'Netherite Leggings',
    maxStackSize: 1,
    durability: 555,
    armorPoints: 6,
    armorToughness: 3,
    enchantability: 15,
    category: 'armor',
  },
  [ITEM.NETHERITE_BOOTS]: {
    id: ITEM.NETHERITE_BOOTS,
    name: 'netherite_boots',
    displayName: 'Netherite Boots',
    maxStackSize: 1,
    durability: 481,
    armorPoints: 3,
    armorToughness: 3,
    enchantability: 15,
    category: 'armor',
  },

  // === FOOD ===
  [ITEM.APPLE]: {
    id: ITEM.APPLE,
    name: 'apple',
    displayName: 'Apple',
    maxStackSize: 64,
    foodPoints: 4,
    saturation: 2.4,
    category: 'food',
  },
  [ITEM.BREAD]: {
    id: ITEM.BREAD,
    name: 'bread',
    displayName: 'Bread',
    maxStackSize: 64,
    foodPoints: 5,
    saturation: 6,
    category: 'food',
  },
  [ITEM.CARROT]: {
    id: ITEM.CARROT,
    name: 'carrot',
    displayName: 'Carrot',
    maxStackSize: 64,
    foodPoints: 3,
    saturation: 3.6,
    category: 'food',
  },
  [ITEM.POTATO]: {
    id: ITEM.POTATO,
    name: 'potato',
    displayName: 'Potato',
    maxStackSize: 64,
    foodPoints: 1,
    saturation: 0.6,
    category: 'food',
  },
  [ITEM.BAKED_POTATO]: {
    id: ITEM.BAKED_POTATO,
    name: 'baked_potato',
    displayName: 'Baked Potato',
    maxStackSize: 64,
    foodPoints: 5,
    saturation: 7.2,
    category: 'food',
  },
  [ITEM.COOKED_BEEF]: {
    id: ITEM.COOKED_BEEF,
    name: 'cooked_beef',
    displayName: 'Steak',
    maxStackSize: 64,
    foodPoints: 8,
    saturation: 12.8,
    category: 'food',
  },
  [ITEM.RAW_BEEF]: {
    id: ITEM.RAW_BEEF,
    name: 'beef',
    displayName: 'Raw Beef',
    maxStackSize: 64,
    foodPoints: 3,
    saturation: 1.8,
    category: 'food',
  },
  [ITEM.COOKED_PORKCHOP]: {
    id: ITEM.COOKED_PORKCHOP,
    name: 'cooked_porkchop',
    displayName: 'Cooked Porkchop',
    maxStackSize: 64,
    foodPoints: 8,
    saturation: 12.8,
    category: 'food',
  },
  [ITEM.PORKCHOP]: {
    id: ITEM.PORKCHOP,
    name: 'porkchop',
    displayName: 'Raw Porkchop',
    maxStackSize: 64,
    foodPoints: 3,
    saturation: 1.8,
    category: 'food',
  },
  [ITEM.COOKED_CHICKEN]: {
    id: ITEM.COOKED_CHICKEN,
    name: 'cooked_chicken',
    displayName: 'Cooked Chicken',
    maxStackSize: 64,
    foodPoints: 6,
    saturation: 7.2,
    category: 'food',
  },
  [ITEM.RAW_CHICKEN]: {
    id: ITEM.RAW_CHICKEN,
    name: 'chicken',
    displayName: 'Raw Chicken',
    maxStackSize: 64,
    foodPoints: 2,
    saturation: 1.2,
    category: 'food',
  },
  [ITEM.COOKED_MUTTON]: {
    id: ITEM.COOKED_MUTTON,
    name: 'cooked_mutton',
    displayName: 'Cooked Mutton',
    maxStackSize: 64,
    foodPoints: 6,
    saturation: 9.6,
    category: 'food',
  },
  [ITEM.MUTTON]: {
    id: ITEM.MUTTON,
    name: 'mutton',
    displayName: 'Raw Mutton',
    maxStackSize: 64,
    foodPoints: 2,
    saturation: 1.2,
    category: 'food',
  },
  [ITEM.COOKED_COD]: {
    id: ITEM.COOKED_COD,
    name: 'cooked_cod',
    displayName: 'Cooked Cod',
    maxStackSize: 64,
    foodPoints: 5,
    saturation: 6,
    category: 'food',
  },
  [ITEM.COD]: {
    id: ITEM.COD,
    name: 'cod',
    displayName: 'Raw Cod',
    maxStackSize: 64,
    foodPoints: 5,
    saturation: 6,
    category: 'food',
  },
  [ITEM.COOKED_SALMON]: {
    id: ITEM.COOKED_SALMON,
    name: 'cooked_salmon',
    displayName: 'Cooked Salmon',
    maxStackSize: 64,
    foodPoints: 6,
    saturation: 9.6,
    category: 'food',
  },
  [ITEM.SALMON]: {
    id: ITEM.SALMON,
    name: 'salmon',
    displayName: 'Raw Salmon',
    maxStackSize: 64,
    foodPoints: 2,
    saturation: 0.4,
    category: 'food',
  },
  [ITEM.GOLDEN_APPLE]: {
    id: ITEM.GOLDEN_APPLE,
    name: 'golden_apple',
    displayName: 'Golden Apple',
    maxStackSize: 64,
    foodPoints: 4,
    saturation: 9.6,
    category: 'food',
  },
  [ITEM.GOLDEN_CARROT]: {
    id: ITEM.GOLDEN_CARROT,
    name: 'golden_carrot',
    displayName: 'Golden Carrot',
    maxStackSize: 64,
    foodPoints: 6,
    saturation: 14.4,
    category: 'food',
  },
  [ITEM.COOKIE]: {
    id: ITEM.COOKIE,
    name: 'cookie',
    displayName: 'Cookie',
    maxStackSize: 64,
    foodPoints: 2,
    saturation: 0.4,
    category: 'food',
  },
  [ITEM.MELON_SLICE]: {
    id: ITEM.MELON_SLICE,
    name: 'melon_slice',
    displayName: 'Melon Slice',
    maxStackSize: 64,
    foodPoints: 2,
    saturation: 1.2,
    category: 'food',
  },
  [ITEM.SWEET_BERRIES]: {
    id: ITEM.SWEET_BERRIES,
    name: 'sweet_berries',
    displayName: 'Sweet Berries',
    maxStackSize: 64,
    foodPoints: 2,
    saturation: 0.4,
    category: 'food',
  },
  [ITEM.GLOW_BERRIES_ITEM]: {
    id: ITEM.GLOW_BERRIES_ITEM,
    name: 'glow_berries',
    displayName: 'Glow Berries',
    maxStackSize: 64,
    foodPoints: 2,
    saturation: 0.4,
    category: 'food',
  },
  [ITEM.BEETROOT]: {
    id: ITEM.BEETROOT,
    name: 'beetroot',
    displayName: 'Beetroot',
    maxStackSize: 64,
    foodPoints: 1,
    saturation: 1.2,
    category: 'food',
  },
  [ITEM.BEETROOT_SOUP]: {
    id: ITEM.BEETROOT_SOUP,
    name: 'beetroot_soup',
    displayName: 'Beetroot Soup',
    maxStackSize: 1,
    foodPoints: 6,
    saturation: 7.2,
    category: 'food',
  },
  [ITEM.MUSHROOM_STEW]: {
    id: ITEM.MUSHROOM_STEW,
    name: 'mushroom_stew',
    displayName: 'Mushroom Stew',
    maxStackSize: 1,
    foodPoints: 6,
    saturation: 7.2,
    category: 'food',
  },
  [ITEM.RABBIT_STEW]: {
    id: ITEM.RABBIT_STEW,
    name: 'rabbit_stew',
    displayName: 'Rabbit Stew',
    maxStackSize: 1,
    foodPoints: 10,
    saturation: 12,
    category: 'food',
  },
  [ITEM.SUSPICIOUS_STEW]: {
    id: ITEM.SUSPICIOUS_STEW,
    name: 'suspicious_stew',
    displayName: 'Suspicious Stew',
    maxStackSize: 1,
    foodPoints: 6,
    saturation: 7.2,
    category: 'food',
  },
  [ITEM.PUMPKIN_PIE]: {
    id: ITEM.PUMPKIN_PIE,
    name: 'pumpkin_pie',
    displayName: 'Pumpkin Pie',
    maxStackSize: 64,
    foodPoints: 8,
    saturation: 4.8,
    category: 'food',
  },
  [ITEM.ROTTEN_FLESH]: {
    id: ITEM.ROTTEN_FLESH,
    name: 'rotten_flesh',
    displayName: 'Rotten Flesh',
    maxStackSize: 64,
    foodPoints: 4,
    saturation: 0.8,
    category: 'food',
  },
  [ITEM.SPIDER_EYE]: {
    id: ITEM.SPIDER_EYE,
    name: 'spider_eye',
    displayName: 'Spider Eye',
    maxStackSize: 64,
    foodPoints: 2,
    saturation: 3.2,
    category: 'food',
  },
  [ITEM.DRIED_KELP_ITEM]: {
    id: ITEM.DRIED_KELP_ITEM,
    name: 'dried_kelp',
    displayName: 'Dried Kelp',
    maxStackSize: 64,
    foodPoints: 1,
    saturation: 0.6,
    category: 'food',
  },
  [ITEM.POISONOUS_POTATO]: {
    id: ITEM.POISONOUS_POTATO,
    name: 'poisonous_potato',
    displayName: 'Poisonous Potato',
    maxStackSize: 64,
    foodPoints: 2,
    saturation: 1.2,
    category: 'food',
  },

  // === BUCKETS ===
  [ITEM.BUCKET]: {
    id: ITEM.BUCKET,
    name: 'bucket',
    displayName: 'Bucket',
    maxStackSize: 16,
    category: 'misc',
  },
  [ITEM.WATER_BUCKET]: {
    id: ITEM.WATER_BUCKET,
    name: 'water_bucket',
    displayName: 'Water Bucket',
    maxStackSize: 1,
    category: 'misc',
  },
  [ITEM.LAVA_BUCKET]: {
    id: ITEM.LAVA_BUCKET,
    name: 'lava_bucket',
    displayName: 'Lava Bucket',
    maxStackSize: 1,
    category: 'misc',
  },
  [ITEM.MILK_BUCKET]: {
    id: ITEM.MILK_BUCKET,
    name: 'milk_bucket',
    displayName: 'Milk Bucket',
    maxStackSize: 1,
    category: 'misc',
  },

  // === MISC ===
  [ITEM.NAME_TAG]: {
    id: ITEM.NAME_TAG,
    name: 'name_tag',
    displayName: 'Name Tag',
    maxStackSize: 64,
    category: 'misc',
  },
  [ITEM.LEAD]: {
    id: ITEM.LEAD,
    name: 'lead',
    displayName: 'Lead',
    maxStackSize: 64,
    category: 'misc',
  },
  [ITEM.SADDLE]: {
    id: ITEM.SADDLE,
    name: 'saddle',
    displayName: 'Saddle',
    maxStackSize: 1,
    category: 'misc',
  },
  [ITEM.TOTEM_OF_UNDYING]: {
    id: ITEM.TOTEM_OF_UNDYING,
    name: 'totem_of_undying',
    displayName: 'Totem of Undying',
    maxStackSize: 1,
    category: 'misc',
  },
  [ITEM.CLOCK]: {
    id: ITEM.CLOCK,
    name: 'clock',
    displayName: 'Clock',
    maxStackSize: 64,
    category: 'misc',
  },
  [ITEM.COMPASS]: {
    id: ITEM.COMPASS,
    name: 'compass',
    displayName: 'Compass',
    maxStackSize: 64,
    category: 'misc',
  },
  [ITEM.MAP]: {
    id: ITEM.MAP,
    name: 'map',
    displayName: 'Empty Map',
    maxStackSize: 64,
    category: 'misc',
  },
  [ITEM.FISHING_ROD]: {
    id: ITEM.FISHING_ROD,
    name: 'fishing_rod',
    displayName: 'Fishing Rod',
    maxStackSize: 1,
    durability: 384,
    category: 'tool',
  },

  // === SPAWN EGGS ===
  [ITEM.SPAWN_EGG_ZOMBIE]: {
    id: ITEM.SPAWN_EGG_ZOMBIE,
    name: 'zombie_spawn_egg',
    displayName: 'Zombie Spawn Egg',
    maxStackSize: 64,
    category: 'spawn_egg',
  },
  [ITEM.SPAWN_EGG_SKELETON]: {
    id: ITEM.SPAWN_EGG_SKELETON,
    name: 'skeleton_spawn_egg',
    displayName: 'Skeleton Spawn Egg',
    maxStackSize: 64,
    category: 'spawn_egg',
  },
  [ITEM.SPAWN_EGG_CREEPER]: {
    id: ITEM.SPAWN_EGG_CREEPER,
    name: 'creeper_spawn_egg',
    displayName: 'Creeper Spawn Egg',
    maxStackSize: 64,
    category: 'spawn_egg',
  },
  [ITEM.SPAWN_EGG_SPIDER]: {
    id: ITEM.SPAWN_EGG_SPIDER,
    name: 'spider_spawn_egg',
    displayName: 'Spider Spawn Egg',
    maxStackSize: 64,
    category: 'spawn_egg',
  },
  [ITEM.SPAWN_EGG_ENDERMAN]: {
    id: ITEM.SPAWN_EGG_ENDERMAN,
    name: 'enderman_spawn_egg',
    displayName: 'Enderman Spawn Egg',
    maxStackSize: 64,
    category: 'spawn_egg',
  },
  [ITEM.SPAWN_EGG_COW]: {
    id: ITEM.SPAWN_EGG_COW,
    name: 'cow_spawn_egg',
    displayName: 'Cow Spawn Egg',
    maxStackSize: 64,
    category: 'spawn_egg',
  },
  [ITEM.SPAWN_EGG_PIG]: {
    id: ITEM.SPAWN_EGG_PIG,
    name: 'pig_spawn_egg',
    displayName: 'Pig Spawn Egg',
    maxStackSize: 64,
    category: 'spawn_egg',
  },
  [ITEM.SPAWN_EGG_SHEEP]: {
    id: ITEM.SPAWN_EGG_SHEEP,
    name: 'sheep_spawn_egg',
    displayName: 'Sheep Spawn Egg',
    maxStackSize: 64,
    category: 'spawn_egg',
  },
  [ITEM.SPAWN_EGG_CHICKEN]: {
    id: ITEM.SPAWN_EGG_CHICKEN,
    name: 'chicken_spawn_egg',
    displayName: 'Chicken Spawn Egg',
    maxStackSize: 64,
    category: 'spawn_egg',
  },
  [ITEM.SPAWN_EGG_VILLAGER]: {
    id: ITEM.SPAWN_EGG_VILLAGER,
    name: 'villager_spawn_egg',
    displayName: 'Villager Spawn Egg',
    maxStackSize: 64,
    category: 'spawn_egg',
  },

  // === RECORDS ===
  [ITEM.MUSIC_DISC_13]: {
    id: ITEM.MUSIC_DISC_13,
    name: 'music_disc_13',
    displayName: 'Music Disc - 13',
    maxStackSize: 1,
    category: 'record',
  },
  [ITEM.MUSIC_DISC_CAT]: {
    id: ITEM.MUSIC_DISC_CAT,
    name: 'music_disc_cat',
    displayName: 'Music Disc - Cat',
    maxStackSize: 1,
    category: 'record',
  },
  [ITEM.MUSIC_DISC_BLOCKS]: {
    id: ITEM.MUSIC_DISC_BLOCKS,
    name: 'music_disc_blocks',
    displayName: 'Music Disc - Blocks',
    maxStackSize: 1,
    category: 'record',
  },
  [ITEM.MUSIC_DISC_CHIRP]: {
    id: ITEM.MUSIC_DISC_CHIRP,
    name: 'music_disc_chirp',
    displayName: 'Music Disc - Chirp',
    maxStackSize: 1,
    category: 'record',
  },
  [ITEM.MUSIC_DISC_FAR]: {
    id: ITEM.MUSIC_DISC_FAR,
    name: 'music_disc_far',
    displayName: 'Music Disc - Far',
    maxStackSize: 1,
    category: 'record',
  },
  [ITEM.MUSIC_DISC_MALL]: {
    id: ITEM.MUSIC_DISC_MALL,
    name: 'music_disc_mall',
    displayName: 'Music Disc - Mall',
    maxStackSize: 1,
    category: 'record',
  },
  [ITEM.MUSIC_DISC_MELLOHI]: {
    id: ITEM.MUSIC_DISC_MELLOHI,
    name: 'music_disc_mellohi',
    displayName: 'Music Disc - Mellohi',
    maxStackSize: 1,
    category: 'record',
  },
  [ITEM.MUSIC_DISC_STAL]: {
    id: ITEM.MUSIC_DISC_STAL,
    name: 'music_disc_stal',
    displayName: 'Music Disc - Stal',
    maxStackSize: 1,
    category: 'record',
  },
  [ITEM.MUSIC_DISC_STRAD]: {
    id: ITEM.MUSIC_DISC_STRAD,
    name: 'music_disc_strad',
    displayName: 'Music Disc - Strad',
    maxStackSize: 1,
    category: 'record',
  },
  [ITEM.MUSIC_DISC_WARD]: {
    id: ITEM.MUSIC_DISC_WARD,
    name: 'music_disc_ward',
    displayName: 'Music Disc - Ward',
    maxStackSize: 1,
    category: 'record',
  },
  [ITEM.MUSIC_DISC_11]: {
    id: ITEM.MUSIC_DISC_11,
    name: 'music_disc_11',
    displayName: 'Music Disc - 11',
    maxStackSize: 1,
    category: 'record',
  },
  [ITEM.MUSIC_DISC_WAIT]: {
    id: ITEM.MUSIC_DISC_WAIT,
    name: 'music_disc_wait',
    displayName: 'Music Disc - Wait',
    maxStackSize: 1,
    category: 'record',
  },
  [ITEM.MUSIC_DISC_OTHERSIDE]: {
    id: ITEM.MUSIC_DISC_OTHERSIDE,
    name: 'music_disc_otherside',
    displayName: 'Music Disc - Otherside',
    maxStackSize: 1,
    category: 'record',
  },
  [ITEM.MUSIC_DISC_5]: {
    id: ITEM.MUSIC_DISC_5,
    name: 'music_disc_5',
    displayName: 'Music Disc - 5',
    maxStackSize: 1,
    category: 'record',
  },
  [ITEM.MUSIC_DISC_PIGSTEP]: {
    id: ITEM.MUSIC_DISC_PIGSTEP,
    name: 'music_disc_pigstep',
    displayName: 'Music Disc - Pigstep',
    maxStackSize: 1,
    category: 'record',
  },
  [ITEM.MUSIC_DISC_RELIC]: {
    id: ITEM.MUSIC_DISC_RELIC,
    name: 'music_disc_relic',
    displayName: 'Music Disc - Relic',
    maxStackSize: 1,
    category: 'record',
  },
  [ITEM.MUSIC_DISC_CREATOR]: {
    id: ITEM.MUSIC_DISC_CREATOR,
    name: 'music_disc_creator',
    displayName: 'Music Disc - Creator',
    maxStackSize: 1,
    category: 'record',
  },
  [ITEM.MUSIC_DISC_CREATOR_MUSIC_BOX]: {
    id: ITEM.MUSIC_DISC_CREATOR_MUSIC_BOX,
    name: 'music_disc_creator_music_box',
    displayName: 'Music Disc - Creator (Music Box)',
    maxStackSize: 1,
    category: 'record',
  },
  [ITEM.MUSIC_DISC_PRECIPICE]: {
    id: ITEM.MUSIC_DISC_PRECIPICE,
    name: 'music_disc_precipice',
    displayName: 'Music Disc - Precipice',
    maxStackSize: 1,
    category: 'record',
  },
  [ITEM.MUSIC_DISC_BOUNCE]: {
    id: ITEM.MUSIC_DISC_BOUNCE,
    name: 'music_disc_bounce',
    displayName: 'Music Disc - Bounce',
    maxStackSize: 1,
    category: 'record',
  },

  // === MCE MOB ITEMS ===
  [ITEM.MCE_CHICKEN]: { id: ITEM.MCE_CHICKEN, name: 'mce_chicken', displayName: 'Chicken', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_AMBER_CHICKEN]: { id: ITEM.MCE_AMBER_CHICKEN, name: 'mce_amber_chicken', displayName: 'Amber Chicken', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_MIDNIGHT_CHICKEN]: { id: ITEM.MCE_MIDNIGHT_CHICKEN, name: 'mce_midnight_chicken', displayName: 'Midnight Chicken', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_STORMY_CHICKEN]: { id: ITEM.MCE_STORMY_CHICKEN, name: 'mce_stormy_chicken', displayName: 'Stormy Chicken', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_BRONZED_CHICKEN]: { id: ITEM.MCE_BRONZED_CHICKEN, name: 'mce_bronzed_chicken', displayName: 'Bronzed Chicken', maxStackSize: 64, category: 'misc' },
  [ITEM.MCECLUCKSHROOM]: { id: ITEM.MCECLUCKSHROOM, name: 'mce_cluckshroom', displayName: 'Cluckshroom', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_FANCY_CHICKEN]: { id: ITEM.MCE_FANCY_CHICKEN, name: 'mce_fancy_chicken', displayName: 'Fancy Chicken', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_SKEWBALD_CHICKEN]: { id: ITEM.MCE_SKEWBALD_CHICKEN, name: 'mce_skewbald_chicken', displayName: 'Skewbald Chicken', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_GOLD_CRESTED_CHICKEN]: { id: ITEM.MCE_GOLD_CRESTED_CHICKEN, name: 'mce_gold_crested_chicken', displayName: 'Gold Crested Chicken', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_COW]: { id: ITEM.MCE_COW, name: 'mce_cow', displayName: 'Cow', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_ALBINO_COW]: { id: ITEM.MCE_ALBINO_COW, name: 'mce_albino_cow', displayName: 'Albino Cow', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_ASHEN_COW]: { id: ITEM.MCE_ASHEN_COW, name: 'mce_ashen_cow', displayName: 'Ashen Cow', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_SUNSET_COW]: { id: ITEM.MCE_SUNSET_COW, name: 'mce_sunset_cow', displayName: 'Sunset Cow', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_COOKIE_COW]: { id: ITEM.MCE_COOKIE_COW, name: 'mce_cookie_cow', displayName: 'Cookie Cow', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_WOOLY_COW]: { id: ITEM.MCE_WOOLY_COW, name: 'mce_wooly_cow', displayName: 'Wooly Cow', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_PINTO_COW]: { id: ITEM.MCE_PINTO_COW, name: 'mce_pinto_cow', displayName: 'Pinto Cow', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_MOOBLOOM]: { id: ITEM.MCE_MOOBLOOM, name: 'mce_moobloom', displayName: 'Moobloom', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_MOOLIP]: { id: ITEM.MCE_MOOLIP, name: 'mce_moolip', displayName: 'Moolip', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_CREAM_COW]: { id: ITEM.MCE_CREAM_COW, name: 'mce_cream_cow', displayName: 'Cream Cow', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_DAIRY_COW]: { id: ITEM.MCE_DAIRY_COW, name: 'mce_dairy_cow', displayName: 'Dairy Cow', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_UMBRA_COW]: { id: ITEM.MCE_UMBRA_COW, name: 'mce_umbra_cow', displayName: 'Umbra Cow', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_PIG]: { id: ITEM.MCE_PIG, name: 'mce_pig', displayName: 'Pig', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_PALE_PIG]: { id: ITEM.MCE_PALE_PIG, name: 'mce_pale_pig', displayName: 'Pale Pig', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_PIEBALD_PIG]: { id: ITEM.MCE_PIEBALD_PIG, name: 'mce_piebald_pig', displayName: 'Piebald Pig', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_SPOTTED_PIG]: { id: ITEM.MCE_SPOTTED_PIG, name: 'mce_spotted_pig', displayName: 'Spotted Pig', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_PINK_FOOTED_PIG]: { id: ITEM.MCE_PINK_FOOTED_PIG, name: 'mce_pink_footed_pig', displayName: 'Pink Footed Pig', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_MUDDY_PIG]: { id: ITEM.MCE_MUDDY_PIG, name: 'mce_muddy_pig', displayName: 'Muddy Pig', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_MOTTLED_PIG]: { id: ITEM.MCE_MOTTLED_PIG, name: 'mce_mottled_pig', displayName: 'Mottled Pig', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_SOOTY_PIG]: { id: ITEM.MCE_SOOTY_PIG, name: 'mce_sooty_pig', displayName: 'Sooty Pig', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_DRIED_MUDDY_PIG]: { id: ITEM.MCE_DRIED_MUDDY_PIG, name: 'mce_dried_muddy_pig', displayName: 'Dried Muddy Pig', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_WHITE_SHEEP]: { id: ITEM.MCE_WHITE_SHEEP, name: 'mce_white_sheep', displayName: 'White Sheep', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_FLECKED_SHEEP]: { id: ITEM.MCE_FLECKED_SHEEP, name: 'mce_flecked_sheep', displayName: 'Flecked Sheep', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_INKY_SHEEP]: { id: ITEM.MCE_INKY_SHEEP, name: 'mce_inky_sheep', displayName: 'Inky Sheep', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_ROCKY_SHEEP]: { id: ITEM.MCE_ROCKY_SHEEP, name: 'mce_rocky_sheep', displayName: 'Rocky Sheep', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_PATCHED_SHEEP]: { id: ITEM.MCE_PATCHED_SHEEP, name: 'mce_patched_sheep', displayName: 'Patched Sheep', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_HORNED_SHEEP]: { id: ITEM.MCE_HORNED_SHEEP, name: 'mce_horned_sheep', displayName: 'Horned Sheep', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_RAINBOW_SHEEP]: { id: ITEM.MCE_RAINBOW_SHEEP, name: 'mce_rainbow_sheep', displayName: 'Rainbow Sheep', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_FUZZY_SHEEP]: { id: ITEM.MCE_FUZZY_SHEEP, name: 'mce_fuzzy_sheep', displayName: 'Fuzzy Sheep', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_LONG_NOSE_SHEEP]: { id: ITEM.MCE_LONG_NOSE_SHEEP, name: 'mce_long_nose_sheep', displayName: 'Long Nose Sheep', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_BOLD_STRIPED_RABBIT]: { id: ITEM.MCE_BOLD_STRIPED_RABBIT, name: 'mce_bold_striped_rabbit', displayName: 'Bold Striped Rabbit', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_FRECKLED_RABBIT]: { id: ITEM.MCE_FRECKLED_RABBIT, name: 'mce_freckled_rabbit', displayName: 'Freckled Rabbit', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_HARELEQUIN_RABBIT]: { id: ITEM.MCE_HARELEQUIN_RABBIT, name: 'mce_harelequin_rabbit', displayName: 'Harelequin Rabbit', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_JUMBO_RABBIT]: { id: ITEM.MCE_JUMBO_RABBIT, name: 'mce_jumbo_rabbit', displayName: 'Jumbo Rabbit', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_MUDDY_FOOT_RABBIT]: { id: ITEM.MCE_MUDDY_FOOT_RABBIT, name: 'mce_muddy_foot_rabbit', displayName: 'Muddy Foot Rabbit', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_VESTED_RABBIT]: { id: ITEM.MCE_VESTED_RABBIT, name: 'mce_vested_rabbit', displayName: 'Vested Rabbit', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_FURNACE_GOLEM]: { id: ITEM.MCE_FURNACE_GOLEM, name: 'mce_furnace_golem', displayName: 'Furnace Golem', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_MELON_GOLEM]: { id: ITEM.MCE_MELON_GOLEM, name: 'mce_melon_golem', displayName: 'Melon Golem', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_SKELETON_WOLF]: { id: ITEM.MCE_SKELETON_WOLF, name: 'mce_skeleton_wolf', displayName: 'Skeleton Wolf', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_BONE_SPIDER]: { id: ITEM.MCE_BONE_SPIDER, name: 'mce_bone_spider', displayName: 'Bone Spider', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_BOULDERING_ZOMBIE]: { id: ITEM.MCE_BOULDERING_ZOMBIE, name: 'mce_bouldering_zombie', displayName: 'Bouldering Zombie', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_LOBBER_ZOMBIE]: { id: ITEM.MCE_LOBBER_ZOMBIE, name: 'mce_lobber_zombie', displayName: 'Lobber Zombie', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_VILER_WITCH]: { id: ITEM.MCE_VILER_WITCH, name: 'mce_viler_witch', displayName: 'Viler Witch', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_GLOW_SQUID]: { id: ITEM.MCE_GLOW_SQUID, name: 'mce_glow_squid', displayName: 'Glow Squid', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_JOLLY_LLAMA]: { id: ITEM.MCE_JOLLY_LLAMA, name: 'mce_jolly_llama', displayName: 'Jolly Llama', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_MOB_OF_ME]: { id: ITEM.MCE_MOB_OF_ME, name: 'mce_mob_of_me', displayName: 'Mob of Me', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_TROPICAL_SLIME]: { id: ITEM.MCE_TROPICAL_SLIME, name: 'mce_tropical_slime', displayName: 'Tropical Slime', maxStackSize: 64, category: 'misc' },

  // === MCE EXCLUSIVE ITEMS ===
  [ITEM.MCE_ADVENTURE_CRYSTAL_COMMON]: { id: ITEM.MCE_ADVENTURE_CRYSTAL_COMMON, name: 'mce_adventure_crystal_common', displayName: 'Common Adventure Crystal', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_ADVENTURE_CRYSTAL_UNCOMMON]: { id: ITEM.MCE_ADVENTURE_CRYSTAL_UNCOMMON, name: 'mce_adventure_crystal_uncommon', displayName: 'Uncommon Adventure Crystal', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_ADVENTURE_CRYSTAL_RARE]: { id: ITEM.MCE_ADVENTURE_CRYSTAL_RARE, name: 'mce_adventure_crystal_rare', displayName: 'Rare Adventure Crystal', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_ADVENTURE_CRYSTAL_EPIC]: { id: ITEM.MCE_ADVENTURE_CRYSTAL_EPIC, name: 'mce_adventure_crystal_epic', displayName: 'Epic Adventure Crystal', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_ADVENTURE_CRYSTAL_LEGENDARY]: { id: ITEM.MCE_ADVENTURE_CRYSTAL_LEGENDARY, name: 'mce_adventure_crystal_legendary', displayName: 'Legendary Adventure Crystal', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_BUCKET_OF_MUD]: { id: ITEM.MCE_BUCKET_OF_MUD, name: 'mce_bucket_of_mud', displayName: 'Bucket of Mud', maxStackSize: 1, category: 'misc' },
  [ITEM.MCE_FANCY_FEATHER]: { id: ITEM.MCE_FANCY_FEATHER, name: 'mce_fancy_feather', displayName: 'Fancy Feather', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_HORN]: { id: ITEM.MCE_HORN, name: 'mce_horn', displayName: 'Horn', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_RUBY]: { id: ITEM.MCE_RUBY, name: 'mce_ruby', displayName: 'Ruby', maxStackSize: 64, category: 'material' },
  [ITEM.MCE_RUBY_BLOCK]: { id: ITEM.MCE_RUBY_BLOCK, name: 'mce_ruby_block', displayName: 'Ruby Block', maxStackSize: 64, category: 'material' },
  [ITEM.MCE_BUTTERCUP]: { id: ITEM.MCE_BUTTERCUP, name: 'mce_buttercup', displayName: 'Buttercup', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_PINK_DAISY]: { id: ITEM.MCE_PINK_DAISY, name: 'mce_pink_daisy', displayName: 'Pink Daisy', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_RAINBOW_CARPET]: { id: ITEM.MCE_RAINBOW_CARPET, name: 'mce_rainbow_carpet', displayName: 'Rainbow Carpet', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_RAINBOW_BED]: { id: ITEM.MCE_RAINBOW_BED, name: 'mce_rainbow_bed', displayName: 'Rainbow Bed', maxStackSize: 1, category: 'misc' },
  [ITEM.MCE_RAINBOW_WOOL]: { id: ITEM.MCE_RAINBOW_WOOL, name: 'mce_rainbow_wool', displayName: 'Rainbow Wool', maxStackSize: 64, category: 'misc' },
  [ITEM.MCE_MUD]: { id: ITEM.MCE_MUD, name: 'mce_mud', displayName: 'Mud', maxStackSize: 64, category: 'misc' },

  // === BLOCK-AS-ITEM PROPERTIES ===
  [ITEM.ACACIA_PLANKS]: { id: ITEM.ACACIA_PLANKS, name: 'acacia_planks', displayName: 'Acacia Wood Planks', maxStackSize: 64, category: 'misc' },
  [ITEM.DARK_OAK_PLANKS]: { id: ITEM.DARK_OAK_PLANKS, name: 'dark_oak_planks', displayName: 'Dark Oak Wood Planks', maxStackSize: 64, category: 'misc' },
  [ITEM.BIRCH_LOG]: { id: ITEM.BIRCH_LOG, name: 'birch_log', displayName: 'Birch Log', maxStackSize: 64, category: 'misc' },
  [ITEM.OAK_LOG]: { id: ITEM.OAK_LOG, name: 'oak_log', displayName: 'Oak Log', maxStackSize: 64, category: 'misc' },
  [ITEM.SPRUCE_LOG]: { id: ITEM.SPRUCE_LOG, name: 'spruce_log', displayName: 'Spruce Log', maxStackSize: 64, category: 'misc' },
  [ITEM.BIRCH_LEAVES]: { id: ITEM.BIRCH_LEAVES, name: 'birch_leaves', displayName: 'Birch Leaves', maxStackSize: 64, category: 'misc' },
  [ITEM.OAK_LEAVES]: { id: ITEM.OAK_LEAVES, name: 'oak_leaves', displayName: 'Oak Leaves', maxStackSize: 64, category: 'misc' },
  [ITEM.SPRUCE_LEAVES]: { id: ITEM.SPRUCE_LEAVES, name: 'spruce_leaves', displayName: 'Spruce Leaves', maxStackSize: 64, category: 'misc' },
  [ITEM.BRICK]: { id: ITEM.BRICK, name: 'brick_block', displayName: 'Brick Block', maxStackSize: 64, category: 'misc' },
  [ITEM.CLAY]: { id: ITEM.CLAY, name: 'clay', displayName: 'Clay Block', maxStackSize: 64, category: 'misc' },
  [ITEM.COBBLESTONE_STAIRS]: { id: ITEM.COBBLESTONE_STAIRS, name: 'cobblestone_stairs', displayName: 'Cobblestone Stairs', maxStackSize: 64, category: 'misc' },
  [ITEM.COBBLESTONE_WALL]: { id: ITEM.COBBLESTONE_WALL, name: 'cobblestone_wall', displayName: 'Cobblestone Wall', maxStackSize: 64, category: 'misc' },
  [ITEM.GLASS]: { id: ITEM.GLASS, name: 'glass', displayName: 'Glass', maxStackSize: 64, category: 'misc' },
  [ITEM.IRON_BARS]: { id: ITEM.IRON_BARS, name: 'iron_bars', displayName: 'Iron Bars', maxStackSize: 64, category: 'misc' },
  [ITEM.NOTE_BLOCK]: { id: ITEM.NOTE_BLOCK, name: 'note_block', displayName: 'Note Block', maxStackSize: 64, category: 'misc' },
  [ITEM.OAK_DOOR]: { id: ITEM.OAK_DOOR, name: 'oak_door', displayName: 'Oak Door', maxStackSize: 64, category: 'misc' },
  [ITEM.OAK_FENCE]: { id: ITEM.OAK_FENCE, name: 'oak_fence', displayName: 'Oak Fence', maxStackSize: 64, category: 'misc' },
  [ITEM.OAK_FENCE_GATE]: { id: ITEM.OAK_FENCE_GATE, name: 'oak_fence_gate', displayName: 'Oak Fence Gate', maxStackSize: 64, category: 'misc' },
  [ITEM.OAK_PRESSURE_PLATE]: { id: ITEM.OAK_PRESSURE_PLATE, name: 'oak_pressure_plate', displayName: 'Oak Pressure Plate', maxStackSize: 64, category: 'misc' },
  [ITEM.OAK_STAIRS]: { id: ITEM.OAK_STAIRS, name: 'oak_stairs', displayName: 'Oak Wood Stairs', maxStackSize: 64, category: 'misc' },
  [ITEM.OAK_SLAB]: { id: ITEM.OAK_SLAB, name: 'oak_slab', displayName: 'Oak Wood Slab', maxStackSize: 64, category: 'misc' },
  [ITEM.POLISHED_ANDESITE]: { id: ITEM.POLISHED_ANDESITE, name: 'polished_andesite', displayName: 'Polished Andesite', maxStackSize: 64, category: 'misc' },
  [ITEM.POLISHED_DIORITE]: { id: ITEM.POLISHED_DIORITE, name: 'polished_diorite', displayName: 'Polished Diorite', maxStackSize: 64, category: 'misc' },
  [ITEM.POLISHED_GRANITE]: { id: ITEM.POLISHED_GRANITE, name: 'polished_granite', displayName: 'Polished Granite', maxStackSize: 64, category: 'misc' },
  [ITEM.POWERED_RAIL]: { id: ITEM.POWERED_RAIL, name: 'powered_rail', displayName: 'Powered Rail', maxStackSize: 64, category: 'misc' },
  [ITEM.STONE]: { id: ITEM.STONE, name: 'stone', displayName: 'Stone', maxStackSize: 64, category: 'material' },
  // Block-as-items for tappables
  [ITEM.DIRT]: { id: ITEM.DIRT, name: 'dirt', displayName: 'Dirt', maxStackSize: 64, category: 'material' },
  [ITEM.GRASS]: { id: ITEM.GRASS, name: 'grass_block', displayName: 'Grass Block', maxStackSize: 64, category: 'material' },
  [ITEM.FERN]: { id: ITEM.FERN, name: 'fern', displayName: 'Fern', maxStackSize: 64, category: 'material' },
  [ITEM.LILY_PAD]: { id: ITEM.LILY_PAD, name: 'lily_pad', displayName: 'Lily Pad', maxStackSize: 64, category: 'material' },
  [ITEM.CARVED_PUMPKIN]: { id: ITEM.CARVED_PUMPKIN, name: 'carved_pumpkin', displayName: 'Carved Pumpkin', maxStackSize: 64, category: 'material' },
  [ITEM.COBBLESTONE]: { id: ITEM.COBBLESTONE, name: 'cobblestone', displayName: 'Cobblestone', maxStackSize: 64, category: 'material' },
  [ITEM.GRAVEL]: { id: ITEM.GRAVEL, name: 'gravel', displayName: 'Gravel', maxStackSize: 64, category: 'material' },
  [ITEM.MYCELIUM]: { id: ITEM.MYCELIUM, name: 'mycelium', displayName: 'Mycelium', maxStackSize: 64, category: 'material' },
  [ITEM.SAND]: { id: ITEM.SAND, name: 'sand', displayName: 'Sand', maxStackSize: 64, category: 'material' },
  [ITEM.REDSTONE]: { id: ITEM.REDSTONE, name: 'redstone', displayName: 'Redstone', maxStackSize: 64, category: 'material' },
  [ITEM.OAK_SAPLING]: { id: ITEM.OAK_SAPLING, name: 'oak_sapling', displayName: 'Oak Sapling', maxStackSize: 64, category: 'material' },
  [ITEM.OAK_PLANKS]: { id: ITEM.OAK_PLANKS, name: 'oak_planks', displayName: 'Oak Wood Planks', maxStackSize: 64, category: 'misc' },
  [ITEM.STONE_BRICKS]: { id: ITEM.STONE_BRICKS, name: 'stone_bricks', displayName: 'Stone Bricks', maxStackSize: 64, category: 'misc' },
  [ITEM.POLISHED_ANDESITE_SLAB]: { id: ITEM.POLISHED_ANDESITE_SLAB, name: 'polished_andesite_slab', displayName: 'Polished Andesite Slab', maxStackSize: 64, category: 'misc' },
  [ITEM.POLISHED_ANDESITE_STAIRS]: { id: ITEM.POLISHED_ANDESITE_STAIRS, name: 'polished_andesite_stairs', displayName: 'Polished Andesite Stairs', maxStackSize: 64, category: 'misc' },
  [ITEM.POLISHED_DIORITE_SLAB]: { id: ITEM.POLISHED_DIORITE_SLAB, name: 'polished_diorite_slab', displayName: 'Polished Diorite Slab', maxStackSize: 64, category: 'misc' },
  [ITEM.POLISHED_DIORITE_STAIRS]: { id: ITEM.POLISHED_DIORITE_STAIRS, name: 'polished_diorite_stairs', displayName: 'Polished Diorite Stairs', maxStackSize: 64, category: 'misc' },
  [ITEM.POLISHED_GRANITE_SLAB]: { id: ITEM.POLISHED_GRANITE_SLAB, name: 'polished_granite_slab', displayName: 'Polished Granite Slab', maxStackSize: 64, category: 'misc' },
  [ITEM.REDSTONE_REPEATER]: { id: ITEM.REDSTONE_REPEATER, name: 'redstone_repeater', displayName: 'Redstone Repeater', maxStackSize: 64, category: 'misc' },
};

/**
 * Get item properties by ID.
 */
export function getItemProperties(id: number): ItemProperties | undefined {
  return ITEM_PROPERTIES[id];
}

/**
 * Override filename for items whose wiki PNG doesn't match displayName_Invicon pattern.
 * Key = numeric item ID, value = exact wiki PNG filename (no full URL).
 */
const ITEM_TEXTURE_FILE: Partial<Record<number, string>> = {
  // Music discs — wiki uses Music_Disc_<name>_JE1_BE1.png (lowercase names!)
  [ITEM.MUSIC_DISC_13]: 'Music_Disc_13_JE1_BE1.png',
  [ITEM.MUSIC_DISC_CAT]: 'Music_Disc_cat_JE1_BE1.png',
  [ITEM.MUSIC_DISC_BLOCKS]: 'Music_Disc_blocks_JE1_BE1.png',
  [ITEM.MUSIC_DISC_CHIRP]: 'Music_Disc_chirp_JE1_BE1.png',
  [ITEM.MUSIC_DISC_FAR]: 'Music_Disc_far_JE1_BE1.png',
  [ITEM.MUSIC_DISC_MALL]: 'Music_Disc_mall_JE1_BE1.png',
  [ITEM.MUSIC_DISC_MELLOHI]: 'Music_Disc_mellohi_JE1_BE1.png',
  [ITEM.MUSIC_DISC_STAL]: 'Music_Disc_stal_JE1_BE1.png',
  [ITEM.MUSIC_DISC_STRAD]: 'Music_Disc_strad_JE1_BE1.png',
  [ITEM.MUSIC_DISC_WARD]: 'Music_Disc_ward_JE1_BE1.png',
  [ITEM.MUSIC_DISC_11]: 'Music_Disc_11_JE1_BE1.png',
  [ITEM.MUSIC_DISC_WAIT]: 'Music_Disc_wait_JE1_BE1.png',
  [ITEM.MUSIC_DISC_OTHERSIDE]: 'Music_Disc_otherside_JE1_BE1.png',
  [ITEM.MUSIC_DISC_5]: 'Music_Disc_5_JE1_BE1.png',
  [ITEM.MUSIC_DISC_PIGSTEP]: 'Music_Disc_Pigstep_JE1_BE1.png',
  [ITEM.MUSIC_DISC_RELIC]: 'Music_Disc_Relic_JE1_BE1.png',
  [ITEM.MUSIC_DISC_CREATOR]: 'Music_Disc_Creator_JE1_BE1.png',
  [ITEM.MUSIC_DISC_CREATOR_MUSIC_BOX]: 'Music_Disc_Creator_(Music_Box)_JE1_BE1.png',
  [ITEM.MUSIC_DISC_PRECIPICE]: 'Music_Disc_Precipice_JE1_BE1.png',
  [ITEM.MUSIC_DISC_BOUNCE]: 'Music_Disc_Bounce_JE1_BE1.png',
  // Items without invicons — use JE texture filenames directly
  [ITEM.REDSTONE_DUST]: 'Redstone_Dust_JE1_BE1.png',
  [ITEM.STEAK]: 'Steak_JE1_BE1.png',
  [ITEM.CLOCK]: 'Clock_(texture)_JE1_BE1.png',
  [ITEM.COMPASS]: 'Compass_(texture)_JE1_BE1.png',
};

/**
 * Get item texture filename (not full URL — caller prepends asset path).
 * Wiki uses "Invicon_<Name>.png" pattern for inventory icons.
 */
export function getItemTextureFile(id: number): string | undefined {
  if (ITEM_TEXTURE_FILE[id]) return ITEM_TEXTURE_FILE[id];
  const props = ITEM_PROPERTIES[id];
  if (!props) return undefined;
  return `Invicon_${props.displayName.replace(/ /g, '_')}.png`;
}

/**
 * Get total armor points for a full set of armor.
 */
export function getArmorSetBonus(helmet: number, chestplate: number, leggings: number, boots: number): {
  totalArmor: number;
  totalToughness: number;
} {
  const h = getItemProperties(helmet);
  const c = getItemProperties(chestplate);
  const l = getItemProperties(leggings);
  const b = getItemProperties(boots);
  return {
    totalArmor: (h?.armorPoints ?? 0) + (c?.armorPoints ?? 0) + (l?.armorPoints ?? 0) + (b?.armorPoints ?? 0),
    totalToughness: (h?.armorToughness ?? 0) + (c?.armorToughness ?? 0) + (l?.armorToughness ?? 0) + (b?.armorToughness ?? 0),
  };
}
