/**
 * Texture URL resolver — maps block IDs to minecraft.wiki image URLs.
 * Client loads these PNGs at runtime via three.js TextureLoader.
 * No local texture files — all reference original Mojang assets.
 */

import { BLOCK } from './blocks.js';

/**
 * Base URL/path for block textures.
 * Change to '' for relative path when assets are served locally (e.g. Vite public/).
 * Set to 'https://minecraft.wiki/images/' for direct wiki loading.
 */
export const TEXTURE_BASE = '';

export interface TextureUrlEntry {
  top?: string;
  bottom?: string;
  side?: string;
  front?: string;
  all?: string;
}

const TEXTURE_URLS: Record<number, TextureUrlEntry> = {
  // Core blocks
  [BLOCK.STONE]: { all: 'Stone_(texture)_JE5_BE3.png' },
  [BLOCK.GRASS]: { top: 'Grass_Block_(top_texture)_JE4_BE2.png', side: 'Grass_Block_(side_texture)_JE2_BE2.png', bottom: 'Dirt_(texture)_JE2_BE2.png' },
  [BLOCK.DIRT]: { all: 'Dirt_(texture)_JE2_BE2.png' },
  [BLOCK.COBBLESTONE]: { all: 'Cobblestone_(texture)_JE5_BE3.png' },
  [BLOCK.OAK_PLANKS]: { all: 'Oak_Planks_(texture)_JE6_BE3.png' },
  [BLOCK.OAK_LOG]: { top: 'Oak_Log_(top_texture)_JE5_BE2.png', side: 'Oak_Log_(texture)_JE4_BE2.png', bottom: 'Oak_Log_(top_texture)_JE5_BE2.png' },
  [BLOCK.OAK_LEAVES]: { all: 'Oak_Leaves.png' },
  [BLOCK.BEDROCK]: { all: 'Bedrock_JE2_BE2.png' },
  [BLOCK.SAND]: { all: 'Sand_(texture)_JE5_BE3.png' },
  [BLOCK.GRAVEL]: { all: 'Gravel_(texture)_JE5_BE4.png' },
  [BLOCK.GLASS]: { all: 'Glass_JE4.png' },
  [BLOCK.DEEPSLATE]: { all: 'Deepslate_(UD)_JE3_BE2.png' },
  [BLOCK.RED_SAND]: { all: 'Red_Sand_(texture)_JE4_BE2.png' },
  [BLOCK.GLASS_PANE]: { all: 'Glass_Pane_(top_texture)_JE5_BE2.png' },
  [BLOCK.OAK_SAPLING]: { all: 'Oak_Sapling_JE4.png' },
  [BLOCK.SPRUCE_SAPLING]: { all: 'Spruce_Sapling_JE3_BE2.png' },
  [BLOCK.BIRCH_SAPLING]: { all: 'Birch_Sapling_JE3_BE2.png' },
  [BLOCK.JUNGLE_SAPLING]: { all: 'Jungle_Sapling_JE3_BE2.png' },
  [BLOCK.ACACIA_SAPLING]: { all: 'Acacia_Sapling_JE3_BE2.png' },
  [BLOCK.DARK_OAK_SAPLING]: { all: 'Dark_Oak_Sapling_JE3_BE2.png' },
  [BLOCK.CHERRY_SAPLING]: { all: 'Cherry_Sapling_JE1.png' },
  [BLOCK.OAK_WOOD]: { all: 'Oak_Wood_(texture)_JE4.png' },
  [BLOCK.SPRUCE_WOOD]: { all: 'Spruce_Wood_(texture)_JE4.png' },
  [BLOCK.BIRCH_WOOD]: { all: 'Birch_Wood_(texture)_JE4.png' },
  [BLOCK.JUNGLE_WOOD]: { all: 'Jungle_Wood_(texture)_JE4.png' },
  [BLOCK.ACACIA_WOOD]: { all: 'Acacia_Wood_(texture)_JE4.png' },
  [BLOCK.DARK_OAK_WOOD]: { all: 'Dark_Oak_Wood_(texture)_JE4.png' },
  [BLOCK.MANGROVE_WOOD]: { all: 'Mangrove_Wood_(texture)_JE2.png' },
  [BLOCK.OAK_BUTTON]: { all: 'Oak_Planks_(texture)_JE6_BE3.png' },
  [BLOCK.SPRUCE_TRAPDOOR]: { all: 'Spruce_Trapdoor_(texture)_JE4_BE2.png' },
  [BLOCK.BIRCH_TRAPDOOR]: { all: 'Birch_Trapdoor_(texture)_JE4_BE2.png' },
  [BLOCK.JUNGLE_TRAPDOOR]: { all: 'Jungle_Trapdoor_(texture)_JE4_BE2.png' },
  [BLOCK.ACACIA_TRAPDOOR]: { all: 'Acacia_Trapdoor_(texture)_JE4_BE2.png' },
  [BLOCK.DARK_OAK_TRAPDOOR]: { all: 'Dark_Oak_Trapdoor_(texture)_JE4_BE2.png' },
  [BLOCK.MANGROVE_TRAPDOOR]: { all: 'Mangrove_Trapdoor_JE2.png' },
  [BLOCK.CRIMSON_DOOR]: { all: 'Crimson_Door_(texture)_JE1.png' },
  [BLOCK.WARPED_DOOR]: { all: 'Warped_Door_(texture)_JE1.png' },
  [BLOCK.CRIMSON_TRAPDOOR]: { all: 'Crimson_Trapdoor_(texture)_JE1.png' },
  [BLOCK.WARPED_TRAPDOOR]: { all: 'Warped_Trapdoor_(texture)_JE1.png' },
  [BLOCK.CRIMSON_FENCE]: { all: 'Crimson_Fence_JE1.png' },
  [BLOCK.WARPED_FENCE]: { all: 'Warped_Fence_JE1.png' },
  [BLOCK.CRIMSON_FENCE_GATE]: { all: 'Crimson_Fence_Gate_JE1.png' },
  [BLOCK.WARPED_FENCE_GATE]: { all: 'Warped_Fence_Gate_JE1.png' },
  [BLOCK.CRIMSON_STAIRS]: { all: 'Crimson_Stairs_(texture)_JE1.png' },
  [BLOCK.WARPED_STAIRS]: { all: 'Warped_Stairs_(texture)_JE1.png' },
  [BLOCK.CRIMSON_SLAB]: { all: 'Crimson_Slab_(texture)_JE1.png' },
  [BLOCK.WARPED_SLAB]: { all: 'Warped_Slab_(texture)_JE1.png' },
  [BLOCK.JUKEBOX]: { all: 'Jukebox_(side_texture)_JE7.png' },
  [BLOCK.STONE_BRICK_STAIRS]: { all: 'Stone_Bricks_Stairs_(texture)_JE6.png' },
  [BLOCK.STONE_BRICK_WALL]: { all: 'Stone_Bricks_(texture)_JE6.png' },
  [BLOCK.MANGROVE_FENCE]: { all: 'Mangrove_Fence_JE2.png' },
  [BLOCK.MANGROVE_FENCE_GATE]: { all: 'Mangrove_Fence_Gate_JE2.png' },
  [BLOCK.MANGROVE_PRESSURE_PLATE]: { all: 'Mangrove_Planks_(texture)_JE2.png' },
  [BLOCK.BAMBOO_PRESSURE_PLATE]: { all: 'Bamboo_Planks_JE1.png' },
  [BLOCK.MOB_SPAWNER]: { all: 'Spawner_(texture)_JE7.png' },
  [BLOCK.CHERRY_CARPET]: { all: 'Cherry_Planks_(texture)_JE1.png' },
  [BLOCK.BAMBOO_CARPET]: { all: 'Bamboo_Planks_JE1.png' },
  [BLOCK.IRON_ORE]: { all: 'Iron_Ore_(texture)_JE6_BE4.png' },
  [BLOCK.COAL_ORE]: { all: 'Coal_Ore_(texture)_JE5_BE4.png' },
  [BLOCK.GOLD_ORE]: { all: 'Gold_Ore_(texture)_JE7_BE4.png' },
  [BLOCK.DIAMOND_ORE]: { all: 'Diamond_Ore_(texture)_JE5_BE5.png' },
  [BLOCK.REDSTONE_ORE]: { all: 'Redstone_Ore_(texture)_JE4_BE3.png' },
  [BLOCK.LAPIS_ORE]: { all: 'Lapis_Lazuli_Ore_(texture)_JE4_BE4.png' },
  [BLOCK.OBSIDIAN]: { all: 'Obsidian_(texture)_JE3_BE2.png' },
  [BLOCK.NETHERRACK]: { all: 'Netherrack_(texture)_JE4_BE3.png' },
  [BLOCK.SOUL_SAND]: { all: 'Soul_Sand_(texture)_JE2_BE2.png' },
  [BLOCK.GLOWSTONE]: { all: 'Glowstone_(texture)_JE4_BE3.png' },
  [BLOCK.STONE_BRICK]: { all: 'Stone_Bricks_(texture)_JE3_BE2.png' },
  [BLOCK.BRICK]: { all: 'Bricks_(texture)_JE5_BE3.png' },
  [BLOCK.TNT]: { side: 'TNT_(side_texture)_JE5.png', top: 'TNT_(top_texture)_JE5.png', bottom: 'TNT_(top_texture)_JE5.png' },
  [BLOCK.BOOKSHELF]: { side: 'Bookshelf_(texture)_JE5_BE3.png', top: 'Oak_Planks_(texture)_JE6_BE3.png', bottom: 'Oak_Planks_(texture)_JE6_BE3.png' },
  [BLOCK.SNOW]: { all: 'Snow_(texture)_JE2_BE2.png' },
  [BLOCK.ICE]: { all: 'Ice_(texture)_JE2_BE6.png' },
  [BLOCK.CLAY]: { all: 'Clay_(texture)_JE2_BE2.png' },
  [BLOCK.CACTUS]: { side: 'Cactus_(side_texture)_JE4_BE2.png', top: 'Cactus_(top_texture)_JE4_BE2.png', bottom: 'Cactus_(top_texture)_JE4_BE2.png' },
  [BLOCK.SANDSTONE]: { top: 'Sandstone_(top_texture)_JE5_BE2.png', side: 'Sandstone_(side_texture)_JE4_BE3.png', bottom: 'Sandstone_(top_texture)_JE5_BE2.png' },
  [BLOCK.IRON_BLOCK]: { all: 'Block_of_Iron_(texture)_JE3_BE3.png' },
  [BLOCK.DIAMOND_BLOCK]: { all: 'Block_of_Diamond_(texture)_JE4_BE3.png' },
  [BLOCK.GOLD_BLOCK]: { all: 'Block_of_Gold_(texture)_JE5_BE3.png' },
  [BLOCK.EMERALD_ORE]: { all: 'Emerald_Ore_(texture)_JE4_BE3.png' },
  [BLOCK.EMERALD_BLOCK]: { all: 'Block_of_Emerald_(texture)_JE4_BE3.png' },
  [BLOCK.LAPIS_BLOCK]: { all: 'Block_of_Lapis_Lazuli_(texture)_JE3_BE3.png' },
  [BLOCK.REDSTONE_BLOCK]: { all: 'Block_of_Redstone_(texture)_JE2_BE2.png' },
  [BLOCK.COAL_BLOCK]: { all: 'Block_of_Coal_(texture)_JE3_BE2.png' },
  [BLOCK.CRAFTING_TABLE]: { top: 'Crafting_Table_(top_texture)_JE6_BE3.png', side: 'Crafting_Table_JE4_BE3.png', bottom: 'Oak_Planks_(texture)_JE6_BE3.png' },
  [BLOCK.FURNACE]: { top: 'Furnace_(top_texture)_JE5_BE2.png', bottom: 'Furnace_(top_texture)_JE5_BE2.png', side: 'Furnace_(S)_JE4.png', front: 'Furnace_(S)_JE4.png' },
  [BLOCK.CHEST]: { all: 'Chest_(texture)_JE5_BE3.png' },
  [BLOCK.TORCH]: { all: 'Torch_(texture)_JE5_BE3.png' },
  [BLOCK.LADDER]: { all: 'Ladder_(texture)_JE5_BE3.png' },
  [BLOCK.LEVER]: { all: 'Lever_(texture)_JE5_BE3.png' },
  [BLOCK.OAK_STAIRS]: { all: 'Oak_Stairs_(texture)_JE5.png' },
  [BLOCK.COBBLESTONE_STAIRS]: { all: 'Cobblestone_Stairs_(texture)_JE5.png' },
  [BLOCK.OAK_DOOR]: { side: 'Oak_Door_(top_texture)_JE5_BE3.png' },
  [BLOCK.IRON_DOOR]: { side: 'Iron_Door_(top_texture)_JE5_BE3.png' },
  [BLOCK.OAK_FENCE]: { all: 'Oak_Fence_(texture)_JE5_BE3.png' },
  [BLOCK.OAK_FENCE_GATE]: { all: 'Oak_Fence_Gate_(texture)_JE5_BE3.png' },
  [BLOCK.OAK_PRESSURE_PLATE]: { all: 'Oak_Pressure_Plate_(texture)_JE5_BE3.png' },
  [BLOCK.STONE_PRESSURE_PLATE]: { all: 'Stone_Pressure_Plate_(texture)_JE5_BE3.png' },
  [BLOCK.STONE_BUTTON]: { all: 'Stone_Button_(texture)_JE5_BE3.png' },
  [BLOCK.REDSTONE_TORCH]: { all: 'Redstone_Torch_(texture)_JE5_BE3.png' },
  [BLOCK.PUMPKIN]: { side: 'Pumpkin_(side_texture)_JE5_BE2.png', top: 'Pumpkin_(top_texture)_JE5_BE2.png', bottom: 'Pumpkin_(top_texture)_JE5_BE2.png' },
  [BLOCK.MELON]: { side: 'Melon_(side_texture)_JE5_BE2.png', top: 'Melon_(top_texture)_JE5_BE2.png', bottom: 'Melon_(top_texture)_JE5_BE2.png' },
  [BLOCK.MYCELIUM]: { top: 'Mycelium_(top_texture)_JE2_BE2.png', side: 'Mycelium_(side_texture)_JE3.png', bottom: 'Dirt_(texture)_JE2_BE2.png' },
  [BLOCK.ENCHANTING_TABLE]: { all: 'Enchanting_Table_(top_texture)_JE5_BE2.png' },
  [BLOCK.BREWING_STAND]: { all: 'Brewing_Stand_(texture)_JE5_BE3.png' },
  [BLOCK.END_STONE]: { all: 'End_Stone_(texture)_JE3_BE2.png' },
  [BLOCK.DRAGON_EGG]: { all: 'Dragon_Egg_(texture)_JE5_BE3.png' },
  [BLOCK.NETHER_BRICK]: { all: 'Nether_Bricks_(texture)_JE5_BE3.png' },
  [BLOCK.NETHER_WART]: { all: 'Nether_Wart_(texture)_JE5_BE2.png' },
  [BLOCK.NETHER_BRICK_FENCE]: { all: 'Nether_Brick_Fence_(texture)_JE5_BE3.png' },
  [BLOCK.NETHER_BRICK_STAIRS]: { all: 'Nether_Brick_Stairs_(texture)_JE5.png' },
  [BLOCK.BEACON]: { all: 'Beacon_(texture)_JE5_BE3.png' },
  [BLOCK.COBBLESTONE_WALL]: { all: 'Cobblestone_(texture)_JE5_BE3.png' },
  [BLOCK.ANVIL]: { all: 'Anvil_(texture)_JE5_BE2.png' },
  [BLOCK.HOPPER]: { all: 'Hopper_(texture)_JE5_BE3.png' },
  [BLOCK.QUARTZ_BLOCK]: { top: 'Block_of_Quartz_(top_texture)_JE3_BE3.png', side: 'Block_of_Quartz_(side_texture)_JE3_BE3.png', bottom: 'Block_of_Quartz_(top_texture)_JE3_BE3.png' },
  [BLOCK.QUARTZ_ORE]: { all: 'Nether_Quartz_Ore_(texture)_JE3_BE2.png' },
  [BLOCK.QUARTZ_STAIRS]: { all: 'Quartz_Stairs_(texture)_JE5.png' },
  [BLOCK.ACTIVATOR_RAIL]: { all: 'Activator_Rail_(texture)_JE5_BE3.png' },
  [BLOCK.DETECTOR_RAIL]: { all: 'Detector_Rail_(texture)_JE5_BE3.png' },
  [BLOCK.POWERED_RAIL]: { all: 'Powered_Rail_(texture)_JE5_BE3.png' },
  [BLOCK.TRIPWIRE_HOOK]: { all: 'Tripwire_Hook_(texture)_JE5_BE3.png' },
  [BLOCK.TRIPWIRE]: { all: 'Tripwire_JE5.png' },
  [BLOCK.COMMAND_BLOCK]: { all: 'Command_Block_(texture)_JE5_BE2.png' },
  [BLOCK.HAY_BALE]: { top: 'Hay_Bale_(top_texture)_JE5_BE2.png', side: 'Hay_Bale_(side_texture)_JE5_BE2.png', bottom: 'Hay_Bale_(top_texture)_JE5_BE2.png' },
  [BLOCK.HARDENED_CLAY]: { all: 'Hardened_Clay_(texture)_JE5_BE2.png' },
  [BLOCK.PACKED_ICE]: { all: 'Packed_Ice_(texture)_JE2_BE3.png' },
  [BLOCK.PRISMARINE]: { all: 'Prismarine_(texture)_JE5_BE2.png' },
  [BLOCK.SEA_LANTERN]: { all: 'Sea_Lantern_(texture)_JE5_BE2.png' },
  [BLOCK.SLIME_BLOCK]: { all: 'Slime_Block_(texture)_JE5_BE2.png' },
  [BLOCK.BARRIER]: { all: 'Barrier_JE5_BE2.png' },
  [BLOCK.REDSTONE_LAMP]: { all: 'Redstone_Lamp_(texture)_JE5.png' },
  [BLOCK.ENDER_CHEST]: { all: 'Ender_Chest_(texture)_JE5_BE3.png' },
  [BLOCK.SPRUCE_PLANKS]: { all: 'Spruce_Planks_(texture)_JE5.png' },
  [BLOCK.BIRCH_PLANKS]: { all: 'Birch_Planks_(texture)_JE3_BE2.png' },
  [BLOCK.JUNGLE_PLANKS]: { all: 'Jungle_Planks_(texture)_JE3_BE2.png' },
  [BLOCK.ACACIA_PLANKS]: { all: 'Acacia_Planks_(texture)_JE3_BE2.png' },
  [BLOCK.DARK_OAK_PLANKS]: { all: 'Dark_Oak_Planks_(texture)_JE3_BE2.png' },
  [BLOCK.SPRUCE_LOG]: { top: 'Spruce_Log_(top_texture)_JE4.png', side: 'Spruce_Log_(texture)_JE3_BE2.png', bottom: 'Spruce_Log_(top_texture)_JE4.png' },
  [BLOCK.BIRCH_LOG]: { top: 'Birch_Log_(top_texture)_JE4_BE2.png', side: 'Birch_Log_(texture)_JE3_BE2.png', bottom: 'Birch_Log_(top_texture)_JE4_BE2.png' },
  [BLOCK.JUNGLE_LOG]: { top: 'Jungle_Log_(top_texture)_JE5_BE2.png', side: 'Jungle_Log_(texture)_JE2.png', bottom: 'Jungle_Log_(top_texture)_JE5_BE2.png' },
  [BLOCK.ACACIA_LOG]: { top: 'Acacia_Log_(top_texture)_JE4_BE2.png', side: 'Acacia_Log_(texture)_JE4_BE2.png', bottom: 'Acacia_Log_(top_texture)_JE4_BE2.png' },
  [BLOCK.DARK_OAK_LOG]: { top: 'Dark_Oak_Log_(top_texture)_JE5.png', side: 'Dark_Oak_Log_(texture)_JE3_BE2.png', bottom: 'Dark_Oak_Log_(top_texture)_JE5.png' },
  [BLOCK.SPRUCE_LEAVES]: { all: 'Spruce_Leaves.png' },
  [BLOCK.BIRCH_LEAVES]: { all: 'Birch_Leaves.png' },
  [BLOCK.JUNGLE_LEAVES]: { all: 'Jungle_Leaves.png' },
  [BLOCK.ACACIA_LEAVES]: { all: 'Acacia_Leaves.png' },
  [BLOCK.DARK_OAK_LEAVES]: { all: 'Dark_Oak_Leaves.png' },
  [BLOCK.GRANITE]: { all: 'Granite_(texture)_JE2_BE2.png' },
  [BLOCK.DIORITE]: { all: 'Diorite_(texture)_JE4_BE3.png' },
  [BLOCK.ANDESITE]: { all: 'Andesite_(texture)_JE3_BE2.png' },
  [BLOCK.COARSE_DIRT]: { all: 'Coarse_Dirt_(texture)_JE1_BE1.png' },
  [BLOCK.PODZOL]: { top: 'Podzol_(top_texture)_JE2_BE2.png', side: 'Podzol_(side_texture)_JE1_BE1.png', bottom: 'Dirt_(texture)_JE2_BE2.png' },
  [BLOCK.POLISHED_GRANITE]: { all: 'Polished_Granite_(texture)_JE2_BE2.png' },
  [BLOCK.POLISHED_DIORITE]: { all: 'Polished_Diorite_(texture)_JE2_BE2.png' },
  [BLOCK.POLISHED_ANDESITE]: { all: 'Polished_Andesite_(texture)_JE2_BE2.png' },
  [BLOCK.RED_SANDSTONE]: { top: 'Red_Sandstone_(top_texture)_JE4_BE2.png', side: 'Red_Sandstone_(side_texture)_JE3_BE2.png', bottom: 'Red_Sandstone_(top_texture)_JE4_BE2.png' },
  [BLOCK.RED_SANDSTONE_STAIRS]: { all: 'Red_Sandstone_Stairs_(texture)_JE5.png' },
  [BLOCK.SPRUCE_STAIRS]: { all: 'Spruce_Stairs_(texture)_JE5.png' },
  [BLOCK.BIRCH_STAIRS]: { all: 'Birch_Stairs_(texture)_JE5.png' },
  [BLOCK.JUNGLE_STAIRS]: { all: 'Jungle_Stairs_(texture)_JE5.png' },
  [BLOCK.ACACIA_STAIRS]: { all: 'Acacia_Stairs_(texture)_JE5.png' },
  [BLOCK.DARK_OAK_STAIRS]: { all: 'Dark_Oak_Stairs_(texture)_JE5.png' },
  [BLOCK.SPRUCE_DOOR]: { side: 'Spruce_Door_(top_texture)_JE5_BE3.png' },
  [BLOCK.BIRCH_DOOR]: { side: 'Birch_Door_(top_texture)_JE5_BE3.png' },
  [BLOCK.JUNGLE_DOOR]: { side: 'Jungle_Door_(top_texture)_JE5_BE3.png' },
  [BLOCK.ACACIA_DOOR]: { side: 'Acacia_Door_(top_texture)_JE5_BE3.png' },
  [BLOCK.DARK_OAK_DOOR]: { side: 'Dark_Oak_Door_(top_texture)_JE5_BE3.png' },
  [BLOCK.SPRUCE_FENCE]: { all: 'Spruce_Fence_(texture)_JE5_BE3.png' },
  [BLOCK.BIRCH_FENCE]: { all: 'Birch_Fence_(texture)_JE5_BE3.png' },
  [BLOCK.JUNGLE_FENCE]: { all: 'Jungle_Fence_(texture)_JE5_BE3.png' },
  [BLOCK.ACACIA_FENCE]: { all: 'Acacia_Fence_(texture)_JE5_BE3.png' },
  [BLOCK.DARK_OAK_FENCE]: { all: 'Dark_Oak_Fence_(texture)_JE5_BE3.png' },
  [BLOCK.SPRUCE_FENCE_GATE]: { all: 'Spruce_Fence_Gate_(texture)_JE5_BE3.png' },
  [BLOCK.BIRCH_FENCE_GATE]: { all: 'Birch_Fence_Gate_(texture)_JE5_BE3.png' },
  [BLOCK.JUNGLE_FENCE_GATE]: { all: 'Jungle_Fence_Gate_(texture)_JE5_BE3.png' },
  [BLOCK.ACACIA_FENCE_GATE]: { all: 'Acacia_Fence_Gate_(texture)_JE5_BE3.png' },
  [BLOCK.DARK_OAK_FENCE_GATE]: { all: 'Dark_Oak_Fence_Gate_(texture)_JE5_BE3.png' },
  [BLOCK.END_STONE_BRICKS]: { all: 'End_Stone_Bricks_(texture)_JE2_BE2.png' },
  [BLOCK.PURPUR_BLOCK]: { all: 'Purpur_Block_(texture)_JE5_BE2.png' },
  [BLOCK.PURPUR_PILLAR]: { top: 'Purpur_Pillar_(top_texture)_JE5_BE2.png', side: 'Purpur_Pillar_(side_texture)_JE5_BE2.png', bottom: 'Purpur_Pillar_(top_texture)_JE5_BE2.png' },
  [BLOCK.PURPUR_STAIRS]: { all: 'Purpur_Stairs_(texture)_JE5.png' },
  [BLOCK.PURPUR_SLAB]: { all: 'Purpur_Block_(texture)_JE5_BE2.png' },
  [BLOCK.CHORUS_PLANT]: { all: 'Chorus_Plant_(texture)_JE5_BE2.png' },
  [BLOCK.CHORUS_FLOWER]: { all: 'Chorus_Flower_(texture)_JE5_BE2.png' },
  [BLOCK.END_ROD]: { all: 'End_Rod_(texture)_JE5_BE2.png' },
  [BLOCK.IRON_TRAPDOOR]: { all: 'Iron_Trapdoor_(texture)_JE5_BE3.png' },
  [BLOCK.OAK_TRAPDOOR]: { all: 'Oak_Trapdoor_(texture)_JE5_BE3.png' },
  [BLOCK.OAK_SLAB]: { all: 'Oak_Planks_(texture)_JE6_BE3.png' },
  [BLOCK.COBBLESTONE_SLAB]: { all: 'Cobblestone_(texture)_JE5_BE3.png' },
  [BLOCK.STONE_SLAB]: { all: 'Stone_(texture)_JE5_BE3.png' },
  [BLOCK.BRICK_SLAB]: { all: 'Bricks_(texture)_JE5_BE3.png' },
  [BLOCK.STONE_BRICK_SLAB]: { all: 'Stone_Bricks_(texture)_JE3_BE2.png' },
  [BLOCK.NETHER_BRICK_SLAB]: { all: 'Nether_Bricks_(texture)_JE5_BE3.png' },
  [BLOCK.QUARTZ_SLAB]: { all: 'Block_of_Quartz_(top_texture)_JE3_BE3.png' },
  [BLOCK.SPRUCE_SLAB]: { all: 'Spruce_Planks_(texture)_JE5.png' },
  [BLOCK.BIRCH_SLAB]: { all: 'Birch_Planks_(texture)_JE3_BE2.png' },
  [BLOCK.JUNGLE_SLAB]: { all: 'Jungle_Planks_(texture)_JE3_BE2.png' },
  [BLOCK.ACACIA_SLAB]: { all: 'Acacia_Planks_(texture)_JE3_BE2.png' },
  [BLOCK.DARK_OAK_SLAB]: { all: 'Dark_Oak_Planks_(texture)_JE3_BE2.png' },
  [BLOCK.RED_SANDSTONE_SLAB]: { all: 'Red_Sandstone_(top_texture)_JE4_BE2.png' },
  [BLOCK.PRISMARINE_SLAB]: { all: 'Prismarine_(texture)_JE5_BE2.png' },
  [BLOCK.DARK_PRISMARINE]: { all: 'Dark_Prismarine_(texture)_JE5_BE2.png' },
  [BLOCK.DARK_PRISMARINE_SLAB]: { all: 'Dark_Prismarine_(texture)_JE5_BE2.png' },
  [BLOCK.DARK_PRISMARINE_STAIRS]: { all: 'Dark_Prismarine_(texture)_JE5_BE2.png' },
  [BLOCK.PRISMARINE_STAIRS]: { all: 'Prismarine_(texture)_JE5_BE2.png' },
  [BLOCK.PRISMARINE_BRICKS]: { all: 'Prismarine_Bricks_(texture)_JE5_BE2.png' },
  [BLOCK.PRISMARINE_BRICK_SLAB]: { all: 'Prismarine_Bricks_(texture)_JE5_BE2.png' },
  [BLOCK.PRISMARINE_BRICK_STAIRS]: { all: 'Prismarine_Bricks_(texture)_JE5_BE2.png' },
  [BLOCK.MOSSY_COBBLESTONE]: { all: 'Mossy_Cobblestone_(texture)_JE4_BE3.png' },
  [BLOCK.MOSSY_STONE_BRICK]: { all: 'Mossy_Stone_Bricks_(texture)_JE3_BE2.png' },
  [BLOCK.SMOOTH_STONE]: { all: 'Smooth_Stone_(texture)_JE2_BE2.png' },
  [BLOCK.SMOOTH_SANDSTONE]: { all: 'Smooth_Sandstone_(texture)_JE5_BE2.png' },
  [BLOCK.SMOOTH_RED_SANDSTONE]: { all: 'Smooth_Red_Sandstone_(texture)_JE5_BE2.png' },
  [BLOCK.CHISELED_STONE_BRICKS]: { all: 'Chiseled_Stone_Bricks_(texture)_JE3_BE2.png' },
  [BLOCK.CHISELED_SANDSTONE]: { all: 'Chiseled_Sandstone_(side_texture)_JE4_BE2.png' },
  [BLOCK.CHISELED_RED_SANDSTONE]: { all: 'Chiseled_Red_Sandstone_(side_texture)_JE3_BE2.png' },
  [BLOCK.CUT_SANDSTONE]: { all: 'Cut_Sandstone_(side_texture)_JE3_BE2.png' },
  [BLOCK.CUT_RED_SANDSTONE]: { all: 'Cut_Red_Sandstone_(side_texture)_JE3_BE2.png' },
  [BLOCK.RED_NETHER_BRICK]: { all: 'Red_Nether_Bricks_(texture)_JE5_BE3.png' },
  [BLOCK.BONE_BLOCK]: { top: 'Bone_Block_(top_texture)_JE5_BE2.png', side: 'Bone_Block_(side_texture)_JE5_BE2.png', bottom: 'Bone_Block_(top_texture)_JE5_BE2.png' },
  [BLOCK.TERRACOTTA]: { all: 'Terracotta_(texture)_JE5_BE3.png' },
  [BLOCK.BLACK_TERRACOTTA]: { all: 'Black_Terracotta_(texture)_JE5_BE3.png' },
  [BLOCK.BLUE_TERRACOTTA]: { all: 'Blue_Terracotta_(texture)_JE5_BE3.png' },
  [BLOCK.BROWN_TERRACOTTA]: { all: 'Brown_Terracotta_(texture)_JE5_BE3.png' },
  [BLOCK.CYAN_TERRACOTTA]: { all: 'Cyan_Terracotta_(texture)_JE5_BE3.png' },
  [BLOCK.GRAY_TERRACOTTA]: { all: 'Gray_Terracotta_(texture)_JE5_BE3.png' },
  [BLOCK.GREEN_TERRACOTTA]: { all: 'Green_Terracotta_(texture)_JE5_BE3.png' },
  [BLOCK.LIGHT_BLUE_TERRACOTTA]: { all: 'Light_Blue_Terracotta_(texture)_JE5_BE3.png' },
  [BLOCK.LIGHT_GRAY_TERRACOTTA]: { all: 'Light_Gray_Terracotta_(texture)_JE5_BE3.png' },
  [BLOCK.LIME_TERRACOTTA]: { all: 'Lime_Terracotta_(texture)_JE5_BE3.png' },
  [BLOCK.MAGENTA_TERRACOTTA]: { all: 'Magenta_Terracotta_(texture)_JE5_BE3.png' },
  [BLOCK.ORANGE_TERRACOTTA]: { all: 'Orange_Terracotta_(texture)_JE5_BE3.png' },
  [BLOCK.PINK_TERRACOTTA]: { all: 'Pink_Terracotta_(texture)_JE5_BE3.png' },
  [BLOCK.PURPLE_TERRACOTTA]: { all: 'Purple_Terracotta_(texture)_JE5_BE3.png' },
  [BLOCK.RED_TERRACOTTA]: { all: 'Red_Terracotta_(texture)_JE5_BE3.png' },
  [BLOCK.WHITE_TERRACOTTA]: { all: 'White_Terracotta_(texture)_JE5_BE3.png' },
  [BLOCK.YELLOW_TERRACOTTA]: { all: 'Yellow_Terracotta_(texture)_JE5_BE3.png' },
  [BLOCK.BLACK_GLAZED_TERRACOTTA]: { all: 'Black_Glazed_Terracotta_(texture)_JE5_BE2.png' },
  [BLOCK.BLUE_GLAZED_TERRACOTTA]: { all: 'Blue_Glazed_Terracotta_(texture)_JE5_BE2.png' },
  [BLOCK.BROWN_GLAZED_TERRACOTTA]: { all: 'Brown_Glazed_Terracotta_(texture)_JE5_BE2.png' },
  [BLOCK.CYAN_GLAZED_TERRACOTTA]: { all: 'Cyan_Glazed_Terracotta_(texture)_JE5_BE2.png' },
  [BLOCK.GRAY_GLAZED_TERRACOTTA]: { all: 'Gray_Glazed_Terracotta_(texture)_JE5_BE2.png' },
  [BLOCK.GREEN_GLAZED_TERRACOTTA]: { all: 'Green_Glazed_Terracotta_(texture)_JE5_BE2.png' },
  [BLOCK.LIGHT_BLUE_GLAZED_TERRACOTTA]: { all: 'Light_Blue_Glazed_Terracotta_(texture)_JE5_BE2.png' },
  [BLOCK.LIGHT_GRAY_GLAZED_TERRACOTTA]: { all: 'Light_Gray_Glazed_Terracotta_(texture)_JE5_BE2.png' },
  [BLOCK.LIME_GLAZED_TERRACOTTA]: { all: 'Lime_Glazed_Terracotta_(texture)_JE5_BE2.png' },
  [BLOCK.MAGENTA_GLAZED_TERRACOTTA]: { all: 'Magenta_Glazed_Terracotta_(texture)_JE5_BE2.png' },
  [BLOCK.ORANGE_GLAZED_TERRACOTTA]: { all: 'Orange_Glazed_Terracotta_(texture)_JE5_BE2.png' },
  [BLOCK.PINK_GLAZED_TERRACOTTA]: { all: 'Pink_Glazed_Terracotta_(texture)_JE5_BE2.png' },
  [BLOCK.PURPLE_GLAZED_TERRACOTTA]: { all: 'Purple_Glazed_Terracotta_(texture)_JE5_BE2.png' },
  [BLOCK.RED_GLAZED_TERRACOTTA]: { all: 'Red_Glazed_Terracotta_(texture)_JE5_BE2.png' },
  [BLOCK.WHITE_GLAZED_TERRACOTTA]: { all: 'White_Glazed_Terracotta_(texture)_JE5_BE2.png' },
  [BLOCK.YELLOW_GLAZED_TERRACOTTA]: { all: 'Yellow_Glazed_Terracotta_(texture)_JE5_BE2.png' },
  [BLOCK.WHITE_WOOL]: { all: 'White_Wool_(texture)_JE5_BE3.png' },
  [BLOCK.ORANGE_WOOL]: { all: 'Orange_Wool_(texture)_JE5_BE3.png' },
  [BLOCK.MAGENTA_WOOL]: { all: 'Magenta_Wool_(texture)_JE5_BE3.png' },
  [BLOCK.LIGHT_BLUE_WOOL]: { all: 'Light_Blue_Wool_(texture)_JE5_BE3.png' },
  [BLOCK.YELLOW_WOOL]: { all: 'Yellow_Wool_(texture)_JE5_BE3.png' },
  [BLOCK.LIME_WOOL]: { all: 'Lime_Wool_(texture)_JE5_BE3.png' },
  [BLOCK.PINK_WOOL]: { all: 'Pink_Wool_(texture)_JE5_BE3.png' },
  [BLOCK.GRAY_WOOL]: { all: 'Gray_Wool_(texture)_JE5_BE3.png' },
  [BLOCK.LIGHT_GRAY_WOOL]: { all: 'Light_Gray_Wool_(texture)_JE5_BE3.png' },
  [BLOCK.CYAN_WOOL]: { all: 'Cyan_Wool_(texture)_JE5_BE3.png' },
  [BLOCK.PURPLE_WOOL]: { all: 'Purple_Wool_(texture)_JE5_BE3.png' },
  [BLOCK.BLUE_WOOL]: { all: 'Blue_Wool_(texture)_JE5_BE3.png' },
  [BLOCK.BROWN_WOOL]: { all: 'Brown_Wool_(texture)_JE5_BE3.png' },
  [BLOCK.GREEN_WOOL]: { all: 'Green_Wool_(texture)_JE5_BE3.png' },
  [BLOCK.RED_WOOL]: { all: 'Red_Wool_(texture)_JE5_BE3.png' },
  [BLOCK.BLACK_WOOL]: { all: 'Black_Wool_(texture)_JE5_BE3.png' },
  [BLOCK.NETHER_WART_BLOCK]: { all: 'Nether_Wart_Block_(texture)_JE5_BE3.png' },
  [BLOCK.WET_SPONGE]: { all: 'Wet_Sponge_(texture)_JE5_BE3.png' },
  [BLOCK.VINE]: { all: 'Vine_(texture)_JE5_BE2.png' },
  [BLOCK.LILY_PAD]: { all: 'Lily_Pad_(texture)_JE5_BE2.png' },
  [BLOCK.FARMLAND]: { top: 'Farmland_(wet_texture)_JE2_BE2.png', side: 'Dirt_(texture)_JE2_BE2.png' },
  [BLOCK.WHEAT]: { all: 'Wheat_(texture)_Stage_7_JE5_BE2.png' },
  [BLOCK.FROSTED_ICE]: { all: 'Frosted_Ice_Age_0_(texture)_JE2_BE2.png' },
  [BLOCK.SUGARCANE]: { all: 'Sugar_Cane_(texture)_JE5_BE2.png' },
  [BLOCK.DAYLIGHT_DETECTOR]: { top: 'Daylight_Detector_(top_texture)_JE5_BE2.png', side: 'Daylight_Detector_(side_texture)_JE5_BE2.png' },
  [BLOCK.COMPARATOR]: { all: 'Comparator_(texture)_JE5.png' },
  [BLOCK.REPEATER]: { all: 'Repeater_(texture)_JE5.png' },
  [BLOCK.TRAPPED_CHEST]: { all: 'Chest_(texture)_JE5_BE3.png' },
  [BLOCK.FLOWER_POT]: { all: 'Flower_Pot_(texture)_JE5_BE3.png' },
  [BLOCK.CARROT]: { all: 'Carrots_(texture)_Stage_3_JE5_BE2.png' },
  [BLOCK.POTATO]: { all: 'Potatoes_(texture)_Stage_3_JE5_BE2.png' },
  [BLOCK.BEETROOT]: { all: 'Beetroots_(texture)_Stage_3_JE5_BE2.png' },
  [BLOCK.SKULL]: { all: 'Skeleton_Skull_(texture)_JE5_BE2.png' },
  [BLOCK.BANNER]: { all: 'Oak_Planks_(texture)_JE6_BE3.png' },
  [BLOCK.LIGHT_WEIGHTED_PRESSURE_PLATE]: { all: 'Block_of_Gold_(texture)_JE5_BE3.png' },
  [BLOCK.HEAVY_WEIGHTED_PRESSURE_PLATE]: { all: 'Block_of_Iron_(texture)_JE3_BE3.png' },
  [BLOCK.SPONGE]: { all: 'Sponge_(texture)_JE5_BE3.png' },
  [BLOCK.WATER]: { all: 'Water_JE11.png' },
  [BLOCK.LAVA]: { all: 'Lava_JE12.png' },
  // Deepslate family
  [BLOCK.COBBLED_DEEPSLATE]: { all: 'Cobbled_Deepslate_(texture)_JE2.png' },
  [BLOCK.POLISHED_DEEPSLATE]: { all: 'Polished_Deepslate_(texture)_JE2.png' },
  [BLOCK.DEEPSLATE_BRICKS]: { all: 'Deepslate_Bricks_(texture)_JE2_BE1.png' },
  [BLOCK.DEEPSLATE_TILES]: { all: 'Deepslate_Tiles_(texture)_JE2.png' },
  [BLOCK.CRACKED_DEEPSLATE_BRICKS]: { all: 'Cracked_Deepslate_Bricks_(texture)_JE1.png' },
  [BLOCK.CHISELED_DEEPSLATE]: { all: 'Chiseled_Deepslate_(texture)_JE2.png' },
  [BLOCK.DEEPSLATE_BRICK_STAIRS]: { all: 'Deepslate_Bricks_(texture)_JE2_BE1.png' },
  [BLOCK.DEEPSLATE_BRICK_SLAB]: { all: 'Deepslate_Bricks_(texture)_JE2_BE1.png' },
  [BLOCK.DEEPSLATE_TILE_STAIRS]: { all: 'Deepslate_Tiles_(texture)_JE2.png' },
  [BLOCK.DEEPSLATE_TILE_SLAB]: { all: 'Deepslate_Tiles_(texture)_JE2.png' },
  [BLOCK.DEEPSLATE_BRICK_WALL]: { all: 'Deepslate_Bricks_(texture)_JE2_BE1.png' },
  [BLOCK.DEEPSLATE_TILE_WALL]: { all: 'Deepslate_Tiles_(texture)_JE2.png' },
  [BLOCK.COBBLED_DEEPSLATE_STAIRS]: { all: 'Cobbled_Deepslate_(texture)_JE2.png' },
  [BLOCK.COBBLED_DEEPSLATE_SLAB]: { all: 'Cobbled_Deepslate_(texture)_JE2.png' },
  [BLOCK.COBBLED_DEEPSLATE_WALL]: { all: 'Cobbled_Deepslate_(texture)_JE2.png' },
  // Copper family
  [BLOCK.COPPER_ORE]: { all: 'Copper_Ore_(texture)_JE2_BE2.png' },
  [BLOCK.COPPER_BLOCK]: { all: 'Block_of_Copper_(texture)_JE1_BE1.png' },
  [BLOCK.CUT_COPPER]: { all: 'Cut_Copper_(texture)_JE2_BE1.png' },
  [BLOCK.CUT_COPPER_STAIRS]: { all: 'Cut_Copper_Stairs_(texture)_JE2.png' },
  [BLOCK.CUT_COPPER_SLAB]: { all: 'Cut_Copper_(texture)_JE2_BE1.png' },
  [BLOCK.COPPER_DOOR]: { side: 'Copper_Door_(top_texture)_JE2.png' },
  [BLOCK.COPPER_TRAPDOOR]: { all: 'Copper_Trapdoor_(texture)_JE2.png' },
  [BLOCK.COPPER_GRATE]: { all: 'Copper_Grate_(texture)_JE1.png' },
  [BLOCK.COPPER_BULB]: { all: 'Copper_Bulb_(texture)_JE2.png' },
  [BLOCK.COPPER_TORCH]: { all: 'Torch_(texture)_JE5_BE3.png' },
  [BLOCK.COPPER_LANTERN]: { all: 'Lantern_(texture)_JE5_BE3.png' },
  [BLOCK.COPPER_BARS]: { all: 'Iron_Bars_(texture)_JE5_BE3.png' },
  [BLOCK.COPPER_CHAIN]: { all: 'Chain_(texture)_JE5_BE2.png' },
  [BLOCK.COPPER_CHEST]: { all: 'Chest_(texture)_JE5_BE3.png' },
  [BLOCK.WAXED_COPPER_BLOCK]: { all: 'Block_of_Copper_(texture)_JE1_BE1.png' },
  [BLOCK.WAXED_CUT_COPPER]: { all: 'Cut_Copper_(texture)_JE2_BE1.png' },
  [BLOCK.WAXED_CUT_COPPER_STAIRS]: { all: 'Cut_Copper_Stairs_(texture)_JE2.png' },
  [BLOCK.WAXED_CUT_COPPER_SLAB]: { all: 'Cut_Copper_(texture)_JE2_BE1.png' },
  [BLOCK.WEATHERED_COPPER]: { all: 'Weathered_Copper_(texture)_JE1_BE1.png' },
  [BLOCK.OXIDIZED_COPPER]: { all: 'Oxidized_Copper_(texture)_JE1_BE1.png' },
  // Tuff family
  [BLOCK.TUFF]: { all: 'Tuff_(texture)_JE1.png' },
  [BLOCK.POLISHED_TUFF]: { all: 'Polished_Tuff_(texture).png' },
  [BLOCK.TUFF_BRICKS]: { all: 'Tuff_Bricks_(texture).png' },
  [BLOCK.CHISELED_TUFF_BRICKS]: { all: 'Chiseled_Tuff_Bricks_(texture).png' },
  [BLOCK.TUFF_STAIRS]: { all: 'Tuff_(texture)_JE1.png' },
  [BLOCK.TUFF_SLAB]: { all: 'Tuff_(texture)_JE1.png' },
  [BLOCK.TUFF_WALL]: { all: 'Tuff_(texture)_JE1.png' },
  [BLOCK.CHISELED_TUFF]: { all: 'Chiseled_Tuff_(texture).png' },
  // Sculk family
  [BLOCK.SCULK]: { all: 'Sculk_(texture)_JE1.png' },
  [BLOCK.SCULK_VEIN]: { all: 'Sculk_Vein_(texture)_JE1.png' },
  [BLOCK.SCULK_SENSOR]: { all: 'Sculk_Sensor_(texture)_JE1.png' },
  [BLOCK.SCULK_CATALYST]: { all: 'Sculk_Catalyst_(texture)_JE1.png' },
  [BLOCK.SCULK_SHRIEKER]: { all: 'Sculk_Shrieker_(texture)_JE1.png' },
  [BLOCK.SCULK_CHARGE]: { all: 'Sculk_(texture)_JE1.png' },
  // Moss/Azalea family
  [BLOCK.MOSS_BLOCK]: { all: 'Moss_Block_(texture)_JE1.png' },
  [BLOCK.MOSS_CARPET]: { all: 'Moss_Block_(texture)_JE1.png' },
  [BLOCK.AZALEA]: { all: 'Azalea_(texture)_JE1.png' },
  [BLOCK.FLOWERING_AZALEA]: { all: 'Flowering_Azalea_(texture)_JE1.png' },
  [BLOCK.AZALEA_LEAVES]: { all: 'Azalea_Leaves_(texture)_JE1.png' },
  [BLOCK.MOSSY_COBBLESTONE_SLAB]: { all: 'Mossy_Cobblestone_(texture)_JE4_BE3.png' },
  [BLOCK.MOSSY_COBBLESTONE_STAIRS]: { all: 'Mossy_Cobblestone_(texture)_JE4_BE3.png' },
  [BLOCK.MOSSY_STONE_BRICK_SLAB]: { all: 'Mossy_Stone_Bricks_(texture)_JE3_BE2.png' },
  [BLOCK.MOSSY_STONE_BRICK_STAIRS]: { all: 'Mossy_Stone_Bricks_(texture)_JE3_BE2.png' },
  [BLOCK.MOSSY_STONE_BRICK_WALL]: { all: 'Mossy_Stone_Bricks_(texture)_JE3_BE2.png' },
  // Cherry family
  [BLOCK.CHERRY_LOG]: { top: 'Cherry_Log_(top_texture)_JE1.png', side: 'Cherry_Log_(texture)_JE1.png', bottom: 'Cherry_Log_(top_texture)_JE1.png' },
  [BLOCK.CHERRY_PLANKS]: { all: 'Cherry_Planks_(texture)_JE1.png' },
  [BLOCK.CHERRY_LEAVES]: { all: 'Cherry_Leaves_(texture)_JE1.png' },
  [BLOCK.CHERRY_DOOR]: { side: 'Cherry_Door_(top_texture)_JE1.png' },
  [BLOCK.CHERRY_STAIRS]: { all: 'Cherry_Planks_(texture)_JE1.png' },
  [BLOCK.CHERRY_SLAB]: { all: 'Cherry_Planks_(texture)_JE1.png' },
  [BLOCK.CHERRY_FENCE]: { all: 'Cherry_Fence_(texture)_JE1.png' },
  [BLOCK.CHERRY_FENCE_GATE]: { all: 'Cherry_Fence_Gate_(texture)_JE1.png' },
  [BLOCK.CHERRY_SIGN]: { all: 'Cherry_Planks_(texture)_JE1.png' },
  [BLOCK.CHERRY_TRAPDOOR]: { all: 'Cherry_Trapdoor_(texture)_JE1.png' },
  [BLOCK.CHERRY_WOOD]: { all: 'Cherry_Wood_(texture)_JE1.png' },
  [BLOCK.STRIPPED_CHERRY_LOG]: { top: 'Stripped_Cherry_Log_(top_texture)_JE1.png', side: 'Stripped_Cherry_Log_(texture)_JE1.png', bottom: 'Stripped_Cherry_Log_(top_texture)_JE1.png' },
  // Mangrove family
  [BLOCK.MANGROVE_LOG]: { top: 'Mangrove_Log_(top_texture)_JE1.png', side: 'Mangrove_Log_(texture)_JE1.png', bottom: 'Mangrove_Log_(top_texture)_JE1.png' },
  [BLOCK.MANGROVE_PLANKS]: { all: 'Mangrove_Planks_(texture)_JE1.png' },
  [BLOCK.MANGROVE_ROOTS]: { all: 'Mangrove_Roots_(texture)_JE1.png' },
  [BLOCK.MUDDY_MANGROVE_ROOTS]: { all: 'Muddy_Mangrove_Roots_(texture)_JE1.png' },
  [BLOCK.PROPAGULE]: { all: 'Propagule_(texture)_JE1.png' },
  [BLOCK.MANGROVE_DOOR]: { side: 'Mangrove_Door_(top_texture)_JE1.png' },
  [BLOCK.MANGROVE_STAIRS]: { all: 'Mangrove_Planks_(texture)_JE1.png' },
  [BLOCK.MANGROVE_SLAB]: { all: 'Mangrove_Planks_(texture)_JE1.png' },
  // Bamboo family
  [BLOCK.BAMBOO_BLOCK]: { top: 'Bamboo_Block_(top_texture)_JE1.png', side: 'Bamboo_Block_(texture)_JE1.png', bottom: 'Bamboo_Block_(top_texture)_JE1.png' },
  [BLOCK.BAMBOO_PLANKS]: { all: 'Bamboo_Planks_(texture)_JE1.png' },
  [BLOCK.BAMBOO_MOSAIC]: { all: 'Bamboo_Mosaic_(texture)_JE1.png' },
  [BLOCK.BAMBOO_DOOR]: { side: 'Bamboo_Door_(top_texture)_JE1.png' },
  [BLOCK.BAMBOO_STAIRS]: { all: 'Bamboo_Planks_(texture)_JE1.png' },
  [BLOCK.BAMBOO_SLAB]: { all: 'Bamboo_Planks_(texture)_JE1.png' },
  [BLOCK.BAMBOO_FENCE]: { all: 'Bamboo_Fence_(texture)_JE1.png' },
  [BLOCK.BAMBOO_FENCE_GATE]: { all: 'Bamboo_Fence_Gate_(texture)_JE1.png' },
  [BLOCK.BAMBOO_SIGN]: { all: 'Bamboo_Planks_(texture)_JE1.png' },
  [BLOCK.BAMBOO_TRAPDOOR]: { all: 'Bamboo_Trapdoor_(texture)_JE1.png' },
  [BLOCK.BAMBOO_MOSAIC_STAIRS]: { all: 'Bamboo_Mosaic_(texture)_JE1.png' },
  [BLOCK.BAMBOO_MOSAIC_SLAB]: { all: 'Bamboo_Mosaic_(texture)_JE1.png' },
  // Resin family
  [BLOCK.RESIN_BLOCK]: { all: 'Resin_Bricks_JE1_BE2.png' },
  [BLOCK.RESIN_BRICKS]: { all: 'Resin_Bricks_JE1_BE2.png' },
  [BLOCK.RESIN_BRICK_STAIRS]: { all: 'Resin_Bricks_JE1_BE2.png' },
  [BLOCK.RESIN_BRICK_SLAB]: { all: 'Resin_Bricks_JE1_BE2.png' },
  [BLOCK.CHISELED_RESIN_BRICKS]: { all: 'Chiseled_Resin_Bricks_JE2_BE3.png' },
  [BLOCK.RESIN_BRICK_WALL]: { all: 'Resin_Bricks_JE1_BE2.png' },
  // Misc blocks
  [BLOCK.DRIED_KELP_BLOCK]: { all: 'Dried_Kelp_Block_(texture)_JE5_BE2.png' },
  [BLOCK.TARGET]: { all: 'Target_(texture)_JE1.png' },
  [BLOCK.LODESTONE]: { all: 'Lodestone_(texture)_JE1.png' },
  [BLOCK.NETHER_GOLD_ORE]: { all: 'Nether_Gold_Ore_(texture)_JE2_BE1.png' },
  [BLOCK.ANCIENT_DEBRIS]: { top: 'Ancient_Debris_(top_texture)_JE1_BE1.png', side: 'Ancient_Debris_(side_texture)_JE1_BE1.png', bottom: 'Ancient_Debris_(top_texture)_JE1_BE1.png' },
  [BLOCK.NETHERITE_BLOCK]: { all: 'Block_of_Netherite_(texture)_JE1_BE1.png' },
  [BLOCK.CRYING_OBSIDIAN]: { all: 'Crying_Obsidian_(texture)_JE1_BE1.png' },
  [BLOCK.BLACKSTONE]: { all: 'Blackstone_(texture)_JE3.png' },
  [BLOCK.POLISHED_BLACKSTONE]: { all: 'Polished_Blackstone_(texture)_JE1_BE1.png' },
  [BLOCK.POLISHED_BLACKSTONE_BRICKS]: { all: 'Polished_Blackstone_Bricks_(texture)_JE2_BE2.png' },
  [BLOCK.GILDED_BLACKSTONE]: { all: 'Gilded_Blackstone_(texture)_JE2.png' },
  [BLOCK.SOUL_SOIL]: { all: 'Soul_Soil_(texture)_JE1_BE1.png' },
  [BLOCK.BASALT]: { top: 'Basalt_(top_texture)_JE1_BE1.png', side: 'Basalt_(side_texture)_JE1_BE1.png', bottom: 'Basalt_(top_texture)_JE1_BE1.png' },
  [BLOCK.SMOOTH_BASALT]: { all: 'Smooth_Basalt_(texture)_JE1.png' },
  [BLOCK.CRIMSON_STEM]: { top: 'Crimson_Stem_(top_texture)_JE1.png', side: 'Crimson_Stem_(texture)_JE1.png', bottom: 'Crimson_Stem_(top_texture)_JE1.png' },
  [BLOCK.WARPED_STEM]: { top: 'Warped_Stem_(top_texture)_JE1.png', side: 'Warped_Stem_(texture)_JE1.png', bottom: 'Warped_Stem_(top_texture)_JE1.png' },
  [BLOCK.CRIMSON_PLANKS]: { all: 'Crimson_Planks_(texture)_JE1.png' },
  [BLOCK.WARPED_PLANKS]: { all: 'Warped_Planks_(texture)_JE1.png' },
  [BLOCK.NETHER_SPROUTS]: { all: 'Nether_Sprouts_(texture)_JE1.png' },
  [BLOCK.TWISTING_VINES]: { all: 'Twisting_Vines_(texture)_JE1.png' },
  [BLOCK.WEEPING_VINES]: { all: 'Weeping_Vines_(texture)_JE1.png' },
  [BLOCK.WARPED_NYLIUM]: { top: 'Warped_Nylium_(top_texture)_JE1_BE1.png', side: 'Warped_Nylium_(side_texture)_JE1_BE1.png', bottom: 'Netherrack_(texture)_JE4_BE3.png' },
  [BLOCK.CRIMSON_NYLIUM]: { top: 'Crimson_Nylium_(top_texture)_JE1_BE1.png', side: 'Crimson_Nylium_(side_texture)_JE1_BE1.png', bottom: 'Netherrack_(texture)_JE4_BE3.png' },
  [BLOCK.WARPED_FUNGUS]: { all: 'Warped_Fungus_(texture)_JE1.png' },
  [BLOCK.CRIMSON_FUNGUS]: { all: 'Crimson_Fungus_(texture)_JE1.png' },
  [BLOCK.SHROOMLIGHT]: { all: 'Shroomlight_(texture)_JE1.png' },
  [BLOCK.WARPED_WART_BLOCK]: { all: 'Warped_Wart_Block_(texture)_JE1.png' },
  [BLOCK.CRIMSON_ROOTS]: { all: 'Crimson_Roots_(texture)_JE1.png' },
  [BLOCK.WARPED_ROOTS]: { all: 'Warped_Roots_(texture)_JE1.png' },
  [BLOCK.PEARLESCENT_FROGLIGHT]: { all: 'Pearlescent_Froglight_(texture)_JE1.png' },
  [BLOCK.VERDANT_FROGLIGHT]: { all: 'Verdant_Froglight_(texture)_JE1.png' },
  [BLOCK.OCHRE_FROGLIGHT]: { all: 'Ochre_Froglight_(texture)_JE1.png' },
  [BLOCK.DECORATED_POT]: { all: 'Decorated_Pot_(texture)_JE1.png' },
  [BLOCK.SUSPICIOUS_SAND]: { all: 'Suspicious_Sand_(texture)_JE1.png' },
  [BLOCK.SUSPICIOUS_GRAVEL]: { all: 'Suspicious_Gravel_(texture)_JE1.png' },
  [BLOCK.TORCHFLOWER]: { all: 'Torchflower_(texture)_JE1.png' },
  [BLOCK.PITCHER_PLANT]: { all: 'Pitcher_Plant_(texture)_JE1.png' },
  [BLOCK.SNIFFER_EGG]: { all: 'Sniffer_Egg_(texture)_JE1.png' },
  [BLOCK.SPORE_BLOSSOM]: { all: 'Spore_Blossom_(texture)_JE1.png' },
  [BLOCK.BIG_DRIPLEAF]: { all: 'Big_Dripleaf_(texture)_JE1.png' },
  [BLOCK.SMALL_DRIPLEAF]: { all: 'Small_Dripleaf_(texture)_JE1.png' },
  [BLOCK.HANGING_ROOTS]: { all: 'Hanging_Roots_(texture)_JE1.png' },
  [BLOCK.ROOTED_DIRT]: { all: 'Rooted_Dirt_(texture)_JE1.png' },
  [BLOCK.PACKED_MUD]: { all: 'Packed_Mud_(texture)_JE1.png' },
  [BLOCK.MUD_BRICKS]: { all: 'Mud_Bricks_(texture)_JE1.png' },
  [BLOCK.MUD_BRICK_STAIRS]: { all: 'Mud_Bricks_(texture)_JE1.png' },
  [BLOCK.MUD_BRICK_SLAB]: { all: 'Mud_Bricks_(texture)_JE1.png' },
  [BLOCK.MUD_BRICK_WALL]: { all: 'Mud_Bricks_(texture)_JE1.png' },
  [BLOCK.REINFORCED_DEEPSLATE]: { all: 'Reinforced_Deepslate_(texture)_JE1.png' },
  [BLOCK.CAMPFIRE]: { all: 'Campfire_(texture)_JE1.png' },
  [BLOCK.SOUL_CAMPFIRE]: { all: 'Soul_Campfire_(texture)_JE1.png' },
  [BLOCK.BEE_NEST]: { all: 'Bee_Nest_(top_texture)_JE1.png' },
  [BLOCK.BEEHIVE]: { all: 'Beehive_(texture)_JE1.png' },
  [BLOCK.HONEY_BLOCK]: { all: 'Honey_Block_(texture)_JE1.png' },
  [BLOCK.HONEYCOMB_BLOCK]: { all: 'Honeycomb_Block_(texture)_JE1.png' },
  [BLOCK.LIGHTNING_ROD]: { all: 'Lightning_Rod_(texture)_JE1.png' },
  [BLOCK.SCAFFOLDING]: { all: 'Scaffolding_(texture)_JE1.png' },
  [BLOCK.BARREL]: { all: 'Barrel_(texture)_JE1.png' },
  [BLOCK.SMOKER]: { top: 'Smoker_(top_texture)_JE1.png', bottom: 'Smoker_(top_texture)_JE1.png', side: 'Smoker_(side_texture)_JE1.png', front: 'Smoker_(front_texture)_JE1.png' },
  [BLOCK.BLAST_FURNACE]: { top: 'Blast_Furnace_(top_texture)_JE1.png', bottom: 'Blast_Furnace_(top_texture)_JE1.png', side: 'Blast_Furnace_(side_texture)_JE1.png', front: 'Blast_Furnace_(front_texture)_JE1.png' },
  [BLOCK.CARTOGRAPHY_TABLE]: { all: 'Cartography_Table_(texture)_JE1.png' },
  [BLOCK.FLETCHING_TABLE]: { all: 'Fletching_Table_(texture)_JE1.png' },
  [BLOCK.GRINDSTONE]: { all: 'Grindstone_(texture)_JE1.png' },
  [BLOCK.LOOM]: { all: 'Loom_(texture)_JE1.png' },
  [BLOCK.STONECUTTER]: { all: 'Stonecutter_(texture)_JE1.png' },
  [BLOCK.SMITHING_TABLE]: { all: 'Smithing_Table_(texture)_JE1.png' },
  [BLOCK.COMPOSTER]: { all: 'Composter_(texture)_JE1.png' },
  [BLOCK.BELL]: { all: 'Bell_(texture)_JE1.png' },
  [BLOCK.LANTERN]: { all: 'Lantern_(texture)_JE5_BE3.png' },
  [BLOCK.SOUL_LANTERN]: { all: 'Soul_Lantern_(texture)_JE5_BE3.png' },
  [BLOCK.POLISHED_TUFF_WALL]: { all: 'Polished_Tuff_(texture).png' },
  [BLOCK.TUFF_BRICK_STAIRS]: { all: 'Tuff_Bricks_(texture).png' },
  [BLOCK.TUFF_BRICK_SLAB]: { all: 'Tuff_Bricks_(texture).png' },
  [BLOCK.TUFF_BRICK_WALL]: { all: 'Tuff_Bricks_(texture).png' },
  [BLOCK.POLISHED_TUFF_STAIRS]: { all: 'Polished_Tuff_(texture).png' },
  [BLOCK.POLISHED_TUFF_SLAB]: { all: 'Polished_Tuff_(texture).png' },
  // Polished variants slabs/stairs
  [BLOCK.POLISHED_ANDESITE_STAIRS]: { all: 'Polished_Andesite_(texture)_JE2_BE2.png' },
  [BLOCK.POLISHED_ANDESITE_SLAB]: { all: 'Polished_Andesite_(texture)_JE2_BE2.png' },
  [BLOCK.POLISHED_DIORITE_STAIRS]: { all: 'Polished_Diorite_(texture)_JE2_BE2.png' },
  [BLOCK.POLISHED_DIORITE_SLAB]: { all: 'Polished_Diorite_(texture)_JE2_BE2.png' },
  [BLOCK.POLISHED_GRANITE_STAIRS]: { all: 'Polished_Granite_(texture)_JE2_BE2.png' },
  [BLOCK.POLISHED_GRANITE_SLAB]: { all: 'Polished_Granite_(texture)_JE2_BE2.png' },
  // Rail and utility
  [BLOCK.RAIL]: { all: 'Rail_(texture)_JE5_BE3.png' },
  [BLOCK.COBWEB]: { all: 'Cobweb_(texture)_JE5_BE3.png' },
  [BLOCK.IRON_BARS]: { all: 'Iron_Bars_(texture)_JE5_BE3.png' },
  [BLOCK.NOTE_BLOCK]: { all: 'Note_Block_(texture)_JE5_BE3.png' },
  [BLOCK.REDSTONE_REPEATER]: { all: 'Redstone_Repeater_(texture)_JE5.png' },
  [BLOCK.WHITE_STAINED_GLASS]: { all: 'Glass_JE4.png' },
  [BLOCK.WHITE_CONCRETE]: { all: 'White_Concrete_(texture)_JE1_BE1.png' },
  [BLOCK.GRAY_CONCRETE]: { all: 'Gray_Concrete_(texture)_JE1_BE1.png' },
  [BLOCK.LIGHT_BLUE_STAINED_GLASS]: { all: 'Light_Blue_Stained_Glass_(texture)_JE1_BE1.png' },
  [BLOCK.WHITE_CARPET]: { all: 'White_Wool_(texture)_JE5_BE3.png' },
  [BLOCK.CONDUIT]: { all: 'Conduit_(texture)_JE1.png' },
  // Nether brick variants
  [BLOCK.CHISELED_NETHER_BRICKS]: { all: 'Chiseled_Nether_Bricks_(texture)_JE1.png' },
  [BLOCK.CRACKED_NETHER_BRICKS]: { all: 'Cracked_Nether_Bricks_(texture)_JE1.png' },
  // Blackstone family
  [BLOCK.POLISHED_BLACKSTONE_STAIRS]: { all: 'Polished_Blackstone_(texture)_JE1_BE1.png' },
  [BLOCK.POLISHED_BLACKSTONE_SLAB]: { all: 'Polished_Blackstone_(texture)_JE1_BE1.png' },
  [BLOCK.POLISHED_BLACKSTONE_BRICK_STAIRS]: { all: 'Polished_Blackstone_Bricks_(texture)_JE2_BE2.png' },
  [BLOCK.POLISHED_BLACKSTONE_BRICK_SLAB]: { all: 'Polished_Blackstone_Bricks_(texture)_JE2_BE2.png' },
  [BLOCK.CHISELED_POLISHED_BLACKSTONE]: { all: 'Chiseled_Polished_Blackstone_(texture)_JE1.png' },
  [BLOCK.BLACKSTONE_WALL]: { all: 'Blackstone_(texture)_JE3.png' },
  [BLOCK.POLISHED_BLACKSTONE_WALL]: { all: 'Polished_Blackstone_(texture)_JE1_BE1.png' },
  [BLOCK.POLISHED_BLACKSTONE_BRICK_WALL]: { all: 'Polished_Blackstone_Bricks_(texture)_JE2_BE2.png' },
  // Wooden buttons
  [BLOCK.CHERRY_BUTTON]: { all: 'Cherry_Planks_(texture)_JE1.png' },
  [BLOCK.CHERRY_PRESSURE_PLATE]: { all: 'Cherry_Planks_(texture)_JE1.png' },
  [BLOCK.MANGROVE_BUTTON]: { all: 'Mangrove_Planks_(texture)_JE1.png' },
  [BLOCK.BAMBOO_BUTTON]: { all: 'Bamboo_Planks_(texture)_JE1.png' },
  // Pillar blocks
  [BLOCK.TUFF_PILAR]: { top: 'Chiseled_Tuff_(texture).png', side: 'Chiseled_Tuff_(texture).png' },
  [BLOCK.OCHRE_FROGLIGHT_PILLAR]: { top: 'Ochre_Froglight_(texture)_JE1.png', side: 'Ochre_Froglight_(texture)_JE1.png' },
  [BLOCK.VERDANT_FROGLIGHT_PILLAR]: { top: 'Verdant_Froglight_(texture)_JE1.png', side: 'Verdant_Froglight_(texture)_JE1.png' },
  [BLOCK.PEARLESCENT_FROGLIGHT_PILLAR]: { top: 'Pearlescent_Froglight_(texture)_JE1.png', side: 'Pearlescent_Froglight_(texture)_JE1.png' },
  // Plants and crops
  [BLOCK.MELON_STEM]: { all: 'Melon_Stem_(texture)_JE5_BE2.png' },
  [BLOCK.PUMPKIN_STEM]: { all: 'Pumpkin_Stem_(texture)_JE5_BE2.png' },
  [BLOCK.COCOA]: { all: 'Cocoa_(texture)_JE5_BE2.png' },
  [BLOCK.SWEET_BERRY_BUSH]: { all: 'Sweet_Berry_Bush_(texture)_JE1.png' },
  [BLOCK.BAMBOO]: { all: 'Bamboo_(texture)_JE1.png' },
  [BLOCK.KELP]: { all: 'Kelp_(texture)_JE1.png' },
  [BLOCK.SEAGRASS]: { all: 'Seagrass_(texture)_JE1.png' },
  [BLOCK.TALL_SEAGRASS]: { all: 'Seagrass_(texture)_JE1.png' },
  [BLOCK.DRIED_KELP]: { all: 'Dried_Kelp_(texture)_JE5_BE2.png' },
  [BLOCK.CAVE_VINES]: { all: 'Cave_Vines_(texture)_JE1.png' },
  [BLOCK.GLOW_BERRIES]: { all: 'Glow_Berries_(texture)_JE1.png' },
  [BLOCK.SPORE_BLOSSOM_PLANT]: { all: 'Spore_Blossom_(texture)_JE1.png' },
};

export function getTextureUrl(blockId: number, face: 'all' | 'top' | 'bottom' | 'side' | 'front'): string | null {
  const entry = TEXTURE_URLS[blockId];
  if (!entry) return null;

  if (face === 'top' && entry.top) return TEXTURE_BASE + entry.top;
  if (face === 'bottom' && entry.bottom) return TEXTURE_BASE + entry.bottom;
  if (face === 'side' && entry.side) return TEXTURE_BASE + entry.side;
  if (face === 'front' && entry.front) return TEXTURE_BASE + entry.front;
  if (entry.all) return TEXTURE_BASE + entry.all;

  // Fallback: try any available variant
  if (entry.side) return TEXTURE_BASE + entry.side;
  if (entry.top) return TEXTURE_BASE + entry.top;
  return null;
}
